/* NextWorld · homes: what a project builds, in the era it stands in
 * One lineage. Every project on your land is drawn in the material of the
 * era the place has reached, so when the settlement levels up the whole
 * town rebuilds itself: canvas at the campground, logs at the fort,
 * timber and stone in the town, brick in the city, steel and glass in
 * the metropolis, white stone at the capital, and the kingdom's houses
 * are the future. The kind of project only tints the building and adds
 * one detail, so a street reads as one place, not a catalogue. */
'use strict';
(function () {
  const { B } = NW;
  /* the accent and the one detail each kind carries through every era */
  const KIND = { home: ['#d9563f', 'chimney'], lab: ['#5a3aa8', 'dish'], library: ['#c9503c', 'sign'], barn: ['#8a5a3a', 'silo'], tower: ['#2f7fd6', 'mast'], workshop: ['#e3a45b', 'stack'], vault: ['#6b7280', 'gate'], datacentre: ['#3fa66b', 'vents'], yard: ['#f2b42a', 'crate'], clinic: ['#e8352f', 'cross'], bank: ['#c9971f', 'coin'] };
  function detail(I, b, gx, gy, H, kind, now) {
    const d = (KIND[kind] || KIND.home)[1], c = (KIND[kind] || KIND.home)[0];
    if (d === 'chimney') { I.chimney(gx + 0.7, gy + 0.2, H + 6, '#9c5a3a'); smokeAt(I, gx + 0.76, gy + 0.26, H + 24, now); }
    else if (d === 'dish') { const q = I.p(gx + 0.75, gy + 0.3, H + 8); I.ctx.fillStyle = '#e6e9ef'; I.ctx.beginPath(); I.ctx.ellipse(q[0], q[1] - 4, 6, 4, -0.5, 0, Math.PI * 2); I.ctx.fill(); I.line(q, [q[0], q[1] - 4], '#8a95a6', 2); }
    else if (d === 'sign') { const s = I.up(I.P(b.D, b.C, 0.5), H * 0.7); I.roundRect(s[0] - 8, s[1] - 4, 16, 7, 2, '#f4f1e8'); I.ctx.fillStyle = c; I.ctx.fillRect(s[0] - 6, s[1] - 2, 5, 3); I.ctx.fillRect(s[0] + 1, s[1] - 2, 5, 3); }
    else if (d === 'silo') { const t = I.box(gx + 0.82, gy + 0.05, 0.16, 0.16, H + 10, '#c9c2b0', 0, { noShadow: true }); I.roof(gx + 0.82, gy + 0.05, 0.16, 0.16, H + 10, 6, '#8a8f98', 0.05); }
    else if (d === 'mast') { const q = I.p(gx + 0.5, gy + 0.5, H + 4); I.line(q, [q[0], q[1] - 26], '#8a95a3', 2); I.blob(q[0], q[1] - 27, 2, Math.floor(now / 500) % 2 ? '#ff4d4d' : '#ffb3b3'); }
    else if (d === 'stack') { I.chimney(gx + 0.75, gy + 0.15, H + 4, '#6b7280'); smokeAt(I, gx + 0.81, gy + 0.21, H + 22, now); }
    else if (d === 'gate') { const a = I.P(b.D, b.C, 0.36), e = I.P(b.D, b.C, 0.64); I.poly([a, e, I.up(e, H * 0.6), I.up(a, H * 0.6)], '#3b4252'); I.line(I.P(a, e, 0.5), I.up(I.P(a, e, 0.5), H * 0.6), '#9aa3b0', 1); }
    else if (d === 'vents') { [0.2, 0.5, 0.8].forEach(u => I.box(gx + u - 0.06, gy + 0.2, 0.12, 0.12, 5, '#dfe5ee', H + 4, { noShadow: true })); }
    else if (d === 'crate') { I.box(gx + 1.02, gy + 0.7, 0.22, 0.22, 7, c, 0, { noShadow: true, tex: 'ribbed' }); }
    else if (d === 'cross') { const s = I.up(I.P(b.D, b.C, 0.5), H * 0.72); I.roundRect(s[0] - 5, s[1] - 5, 10, 10, 2, '#fff'); I.ctx.fillStyle = c; I.ctx.fillRect(s[0] - 1.2, s[1] - 3.5, 2.4, 7); I.ctx.fillRect(s[0] - 3.5, s[1] - 1.2, 7, 2.4); }
    else if (d === 'coin') { const s = I.up(I.P(b.D, b.C, 0.5), H * 0.72); I.blob(s[0], s[1], 4, c); I.ctx.fillStyle = '#4a2b00'; I.ctx.font = '800 5px Baloo 2, system-ui, sans-serif'; I.ctx.textAlign = 'center'; I.ctx.fillText('$', s[0], s[1] + 2); I.ctx.textAlign = 'left'; }
  }
  const accent = kind => (KIND[kind] || KIND.home)[0];
  let live = true; let smokes = [];   /* live: draw the smoke now; otherwise note where it rises so the caller can */
  const smokeAt = (I, gx, gy, z, now) => { if (live) { const q = I.p(gx, gy, z); I.smoke(q[0], q[1], now); } else smokes.push({ gx, gy, z }); };
  /* what a building goes up as: the very building it will be, revealed from
   * the ground up one slice per step, with scaffolding to the height reached */
  /* the terrain's building style: what the walls are made of, how the roof is pitched */
  const STYLES = {
    plains: { wall1: '#a8763f', tex1: 'siding', roof1: '#6b4a2b', wall2: '#f3e6cc', timber: '#5a3a1e', roof2: null, glass: '#5aa0d8', roof: 'gable' },
    forest: { wall1: '#8a5a2e', tex1: 'siding', roof1: '#2f5d3a', wall2: '#c9a06a', timber: '#4a2b17', roof2: '#3f6a4a', glass: '#5f8f7a', roof: 'steep' },
    sandy: { wall1: '#d9b38c', tex1: 'stone', roof1: '#b5643a', wall2: '#e6c9a0', timber: null, roof2: '#b5643a', glass: '#c9a26a', roof: 'flat' },
    island: { wall1: '#e8d9b5', tex1: 'siding', roof1: '#b89a5a', wall2: '#f2e6c8', timber: null, roof2: '#b89a5a', glass: '#5fb0c8', roof: 'thatch', stilts: true },
    mountains: { wall1: '#a9a49a', tex1: 'stone', roof1: '#4b4b4b', wall2: '#d9d2c4', timber: '#5a3a1e', roof2: '#4b4b4b', glass: '#7a93a8', roof: 'steep' },
    snow: { wall1: '#c9a06a', tex1: 'siding', roof1: '#f4f7fa', wall2: '#e8dcc6', timber: '#6b4a2b', roof2: '#f4f7fa', glass: '#8fb6d9', roof: 'steep' },
    rain: { wall1: '#9aa0a3', tex1: 'stone', roof1: '#4f5b66', wall2: '#d8d6cf', timber: null, roof2: '#4f5b66', glass: '#6e8aa0', roof: 'gable' },
    zen: { wall1: '#f4efe4', tex1: 'siding', roof1: '#3d3d3d', wall2: '#f4efe4', timber: '#3d3d3d', roof2: '#3d3d3d', glass: '#8fb3a8', roof: 'pagoda' },
    savanna: { wall1: '#c8925a', tex1: 'stone', roof1: '#b89a5a', wall2: '#dcb27a', timber: null, roof2: '#b89a5a', glass: '#b08a4a', roof: 'thatch' }
  };
  /* a palette that goes together: roofs, bands and doors take turns through it, so a street is varied and never garish */
  const PALETTE = ['#c9503c', '#3f8f6b', '#3b6fb5', '#d9a23a', '#8f5fd1', '#e8845a', '#4fa3c9', '#7a8f3a'];
  const TINT = [0, 0.14, -0.1, 0.26, -0.18, 0.08];
  let STY = STYLES.plains, N = 0, PLACE = {};   /* N: which home on the street this is; PLACE: which side its street is on */
  const wallOf = base => NW.shade(base, TINT[N % TINT.length]);
  const roofOf2 = base => base ? NW.shade(base, TINT[(N + 2) % TINT.length] * 0.5) : PALETTE[N % PALETTE.length];
  const bandOf = () => PALETTE[(N * 3 + 1) % PALETTE.length];
  const setTerrain = key => { STY = STYLES[key] || STYLES.plains; };
  /* the roof the terrain builds: flat in the desert, steep where it snows, thatch on the island, tiered in the garden */
  function roofOf(I, gx, gy, w, d, base, h, colour, wall) {
    if (STY.roof === 'flat') { I.flatRoof(gx, gy, w, d, base, NW.shade(colour, 0.1)); I.box(gx - 0.03, gy - 0.03, w + 0.06, 0.06, 5, wall, base + 4, { noShadow: true }); I.box(gx + w - 0.03, gy - 0.03, 0.06, d + 0.06, 5, wall, base + 4, { noShadow: true }); return; }
    if (STY.roof === 'steep') { I.roof(gx, gy, w, d, base, h * 1.6, colour); return; }
    if (STY.roof === 'thatch') { I.roof(gx, gy, w, d, base, h * 1.15, colour, 0.24); return; }
    if (STY.roof === 'pagoda') { I.roof(gx, gy, w, d, base, h * 0.6, colour, 0.34); I.box(gx + w * 0.22, gy + d * 0.22, w * 0.56, d * 0.56, 12, wall, base + h * 0.6, { noShadow: true }); I.roof(gx + w * 0.22, gy + d * 0.22, w * 0.56, d * 0.56, base + h * 0.6 + 12, h * 0.55, colour, 0.28); return; }
    I.roof(gx, gy, w, d, base, h, colour);
  }
  const stiltsOf = (I, gx, gy, w, d, lift) => { if (!lift) return; [[0, 0], [w, 0], [0, d], [w, d], [w / 2, d], [w, d / 2]].forEach(o => { const q = I.p(gx + o[0], gy + o[1]); I.ctx.fillStyle = '#6b4a2b'; I.ctx.fillRect(q[0] - 1.5, q[1] - lift, 3, lift); }); };
  /* ---- the builder: every home is a set of parameters, not a drawing ----
   * A variant names a footprint, floors, a roof, a wall material and a few features; the builder draws it in the terrain's
   * palette. Each era has its own table of variants, and the table grows with the era (six at the campground, twenty-six
   * in the kingdom), so a street is never the same building twice and a city is never a template. */
  const MAT = { siding: () => STY.wall1, plaster: () => STY.wall2, stone: () => '#b3ada3', brick: () => '#b8553f', glass: () => STY.glass, ribbed: () => '#c9d2dc', canvas: () => '#e9e4d6', composite: () => '#f4f7fa', dark: () => '#3b4252' };
  const TEX = { siding: 'siding', plaster: null, stone: 'stone', brick: 'brick', glass: 'glass', ribbed: 'ribbed', canvas: null, composite: null, dark: null };
  const v = (name, w, d, fl, fh, roof, wall, f, o) => Object.assign({ name, w, d, fl, fh, roof, wall, f: ' ' + f + ' ' }, o || {});
  const VARIANTS = [
    /* 0 campground: canvas and poles */
    [v('ridge tent', 1, 0.8, 1, 22, 'tent', 'canvas', 'awning'), v('dome tent', 0.8, 0.8, 1, 18, 'domeTent', 'canvas', 'porch'), v('tipi', 0.9, 0.9, 1, 34, 'cone', 'canvas', 'smoke'), v('yurt', 1.1, 1.1, 1, 14, 'yurt', 'canvas', 'chimney'), v('lean-to', 1.2, 0.7, 1, 20, 'leanTent', 'canvas', 'stove'), v('bell tent', 1, 1, 1, 26, 'cone', 'canvas', 'porch'), v('pup tents', 1.4, 0.7, 1, 12, 'pups', 'canvas', 'fence'), v('tarp fly', 1.3, 1, 1, 14, 'fly', 'canvas', 'twin')],
    /* 1 fort: logs and stone */
    [v('log cabin', 1.3, 1.3, 1, 29, 'gable', 'siding', 'chimney porch'), v('longhouse', 1.4, 0.8, 1, 26, 'steep', 'siding', 'twin chimney'), v('blockhouse', 1, 1, 2, 22, 'hip', 'siding', 'overhang loft'), v('stilt cabin', 1.2, 1.2, 1, 24, 'gable', 'siding', 'veranda chimney', { lift: 10 }), v('sod house', 1.3, 1.1, 1, 18, 'round', 'stone', 'chimney well'), v('cabin and lean-to', 1.2, 1.2, 1, 26, 'gable', 'siding', 'leanto chimney'), v('stone cottage', 1.2, 1.2, 1, 26, 'steep', 'stone', 'chimney dormer'), v('saltbox', 1.3, 1.3, 2, 20, 'gable', 'siding', 'chimney porch'), v('gate lodge', 1, 1.4, 2, 22, 'gable', 'siding', 'tower fence'), v('trapper hut', 0.9, 0.9, 1, 22, 'steep', 'siding', 'chimney loft')],
    /* 2 town: timber on stone, plaster, the first brick */
    [v('timber frame', 1.4, 1.4, 2, 24, 'gable', 'plaster', 'timber dormer chimney', { base: 1 }), v('shop house', 1.2, 1.4, 2, 24, 'gable', 'plaster', 'shopfront awning', { base: 1 }), v('row twin', 1.4, 1, 2, 22, 'gable', 'brick', 'twin chimney'), v('inn', 1.4, 1.4, 2, 26, 'hip', 'plaster', 'timber balcony chimney', { base: 1 }), v('stone manse', 1.3, 1.3, 2, 26, 'steep', 'stone', 'bay chimney'), v('farmhouse', 1.4, 1.2, 2, 22, 'gable', 'siding', 'porch chimney well'), v('mill cottage', 1, 1.4, 2, 22, 'steep', 'stone', 'dormer loft'), v('turret house', 1.3, 1.3, 2, 24, 'hip', 'plaster', 'tower porch', { base: 1 }), v('chapel house', 1, 1.4, 1, 36, 'steep', 'stone', 'spire arch'), v('cottage', 1.1, 1.1, 1, 22, 'hip', 'plaster', 'chimney fence porch'), v('brick terrace', 1.4, 1.1, 2, 22, 'gable', 'brick', 'chimney awning'), v('coach house', 1.3, 1.2, 2, 22, 'hip', 'siding', 'garage loft chimney')],
    /* 3 city: brick and stone, the first flat roofs */
    [v('brownstone', 1.2, 1.4, 3, 22, 'flat', 'brick', 'bay chimney'), v('corner shop', 1.4, 1.4, 3, 22, 'flat', 'brick', 'shopfront awning escape'), v('tenement', 1.4, 1.2, 4, 20, 'flat', 'brick', 'escape tank'), v('mansard block', 1.4, 1.4, 3, 22, 'mansard', 'stone', 'dormer arch'), v('bay terrace', 1.4, 1, 2, 22, 'gable', 'brick', 'twin bay'), v('warehouse loft', 1.4, 1.4, 3, 24, 'sawtooth', 'brick', 'loft arch'), v('villa', 1.3, 1.3, 2, 24, 'hip', 'plaster', 'veranda columns garage'), v('arcade house', 1.2, 1.4, 3, 22, 'flat', 'stone', 'arch columns balcony'), v('courtyard block', 1.4, 1.4, 3, 20, 'flat', 'brick', 'ring balcony'), v('clock house', 1, 1, 4, 20, 'steep', 'brick', 'tower spire'), v('glass mid-rise', 1.4, 1.4, 4, 22, 'flat', 'glass', 'garden antenna'), v('stone hall', 1.4, 1.2, 3, 24, 'hip', 'stone', 'columns arch chimney'), v('brick walk-up', 1.2, 1.2, 4, 20, 'flat', 'brick', 'escape awning'), v('corner glass', 1.4, 1.2, 3, 24, 'flat', 'glass', 'shopfront balcony'), v('mansard terrace', 1.4, 1, 3, 22, 'mansard', 'brick', 'twin dormer'), v('printworks', 1.4, 1.4, 2, 28, 'sawtooth', 'brick', 'stack loft')],
    /* 4 metropolis: glass and ribbed steel */
    [v('glass mid-rise', 1.4, 1.4, 5, 22, 'flat', 'glass', 'garden antenna'), v('slab tower', 1, 1.4, 8, 20, 'flat', 'glass', 'setback antenna'), v('podium tower', 1.4, 1.4, 2, 24, 'flat', 'glass', 'podium garden', { core: [0.9, 6, 20] }), v('cylinder', 1.2, 1.2, 7, 20, 'flat', 'glass', 'cylinder antenna'), v('twin towers', 1.4, 1, 6, 20, 'flat', 'glass', 'twin skybridge'), v('sawtooth loft', 1.4, 1.4, 3, 24, 'sawtooth', 'ribbed', 'garden tank'), v('crown block', 1.4, 1.4, 6, 20, 'flat', 'glass', 'crown antenna'), v('stepped terraces', 1.4, 1.4, 4, 22, 'flat', 'ribbed', 'steps balcony garden'), v('ribbed walk-up', 1.2, 1.2, 4, 22, 'flat', 'ribbed', 'escape tank awning'), v('glass corner shop', 1.4, 1.2, 3, 24, 'flat', 'glass', 'shopfront awning balcony'), v('tall slab', 1.2, 1.4, 10, 20, 'flat', 'glass', 'setback crown'), v('glass cylinder', 1.3, 1.3, 9, 20, 'flat', 'glass', 'cylinder crown'), v('bridge twins', 1.4, 1.2, 8, 20, 'flat', 'ribbed', 'twin skybridge antenna'), v('roof park', 1.4, 1.4, 4, 24, 'flat', 'glass', 'garden columns'), v('helix block', 1.2, 1.2, 6, 22, 'flat', 'ribbed', 'steps tank'), v('atrium', 1.4, 1.4, 5, 22, 'flat', 'glass', 'ring garden'), v('media tower', 1, 1, 9, 20, 'flat', 'dark', 'antenna crown'), v('terrace twins', 1.4, 1.1, 5, 22, 'flat', 'glass', 'twin balcony'), v('steel loft', 1.4, 1.3, 3, 26, 'sawtooth', 'ribbed', 'loft escape'), v('tower and shop', 1.4, 1.4, 7, 20, 'flat', 'glass', 'shopfront setback')],
    /* 5 capital: white stone and glass */
    [v('colonnade villa', 1.4, 1.4, 2, 28, 'hip', 'composite', 'columns porch garden'), v('domed mansion', 1.4, 1.4, 2, 26, 'dome', 'composite', 'dome columns'), v('spire tower', 1, 1, 9, 18, 'steep', 'glass', 'spire crown'), v('crown tower', 1.4, 1.4, 7, 18, 'flat', 'glass', 'crown helipad'), v('column terrace', 1.4, 1, 3, 24, 'mansard', 'composite', 'columns twin balcony'), v('ring atrium', 1.4, 1.4, 4, 20, 'flat', 'composite', 'ring garden'), v('palace flat', 1.4, 1.4, 3, 24, 'mansard', 'composite', 'arch dormer balcony'), v('garden slab', 1.2, 1.4, 5, 20, 'flat', 'glass', 'garden skybridge'), v('obelisk tower', 0.8, 0.8, 10, 18, 'flat', 'composite', 'setback spire'), v('arcaded block', 1.4, 1.2, 3, 22, 'hip', 'composite', 'arch columns awning'), v('glass ministry', 1.4, 1.4, 6, 20, 'flat', 'glass', 'columns crown'), v('marble twins', 1.4, 1.1, 8, 18, 'flat', 'composite', 'twin crown'), v('embassy', 1.4, 1.4, 3, 26, 'hip', 'composite', 'columns balcony fence'), v('cylinder hall', 1.3, 1.3, 5, 20, 'dome', 'glass', 'cylinder dome'), v('stepped ministry', 1.4, 1.4, 6, 20, 'flat', 'composite', 'steps garden'), v('spire twins', 1.4, 1, 9, 18, 'steep', 'glass', 'twin spire'), v('helipad tower', 1.2, 1.2, 8, 20, 'flat', 'glass', 'helipad antenna'), v('grand arcade', 1.4, 1.4, 4, 22, 'mansard', 'composite', 'arch columns dormer'), v('glass court', 1.4, 1.4, 5, 20, 'flat', 'glass', 'ring balcony'), v('white tower', 1, 1.2, 10, 18, 'flat', 'composite', 'setback crown'), v('senate flats', 1.4, 1.2, 4, 22, 'hip', 'composite', 'balcony columns'), v('dome tower', 1.2, 1.2, 7, 20, 'dome', 'glass', 'dome crown')],
    /* 6 kingdom: composite shells, glass, lit bands; nothing that stood in the capital */
    [v('shell pod', 1.4, 1.4, 4, 26, 'dome', 'composite', 'dome spire glow'), v('stem house', 1.4, 1.4, 1, 30, 'dome', 'composite', 'stem dome glow', { lift: 40 }), v('ring habitat', 1.4, 1.4, 3, 24, 'flat', 'glass', 'ring skybridge glow'), v('cylinder stack', 1, 1, 6, 22, 'flat', 'ribbed', 'cylinder setback glow'), v('twin spires', 1.4, 1, 8, 18, 'steep', 'glass', 'twin spire skybridge'), v('floating disc', 1.4, 1.4, 2, 24, 'flat', 'composite', 'stem helipad ring glow', { lift: 30 }), v('crown tower', 1.2, 1.2, 9, 18, 'flat', 'glass', 'crown antenna glow'), v('dome cluster', 1.4, 1.4, 1, 40, 'dome', 'composite', 'dome twin glow'), v('helipad tower', 1, 1, 7, 20, 'flat', 'ribbed', 'helipad solar'), v('solar terraces', 1.4, 1.4, 4, 22, 'flat', 'glass', 'steps solar garden'), v('sky needle', 0.8, 0.8, 12, 18, 'flat', 'glass', 'spire crown glow'), v('lantern pod', 1.2, 1.2, 3, 26, 'dome', 'glass', 'dome glow stem', { lift: 20 }), v('orbit ring', 1.4, 1.4, 2, 24, 'flat', 'composite', 'ring stem glow', { lift: 24 }), v('cyan twins', 1.4, 1.1, 7, 20, 'flat', 'glass', 'twin crown glow'), v('hover dock', 1.4, 1.4, 2, 22, 'flat', 'ribbed', 'helipad solar antenna'), v('glass egg', 1.2, 1.2, 5, 22, 'dome', 'glass', 'cylinder dome glow'), v('terrace pods', 1.4, 1.4, 3, 24, 'dome', 'composite', 'steps dome garden'), v('light tower', 1, 1, 10, 18, 'flat', 'composite', 'crown glow antenna'), v('dome hall', 1.4, 1.4, 2, 30, 'dome', 'composite', 'dome columns glow'), v('stacked discs', 1.3, 1.3, 5, 22, 'flat', 'composite', 'steps ring glow'), v('bridge spires', 1.4, 1, 9, 18, 'steep', 'glass', 'twin skybridge glow'), v('solar dome', 1.4, 1.4, 3, 24, 'dome', 'glass', 'dome solar'), v('stem twins', 1.4, 1.2, 2, 24, 'flat', 'composite', 'twin stem glow', { lift: 34 }), v('ribbed needle', 0.8, 0.8, 11, 18, 'flat', 'ribbed', 'setback spire glow'), v('garden ring', 1.4, 1.4, 4, 22, 'flat', 'glass', 'ring garden glow'), v('crown pod', 1.3, 1.3, 3, 26, 'dome', 'composite', 'dome crown glow')]
  ];
  /* which variant this home is: the street cycles through the era's table, so neighbours never match */
  const pick = era => { const list = VARIANTS[era] || VARIANTS[1]; return list[(N * 7 + era * 3) % list.length]; };
  const ROOF = [null, null, null, '#4b5563', '#9aa3b0', '#e9e2d0', '#c9d2dc'];
  /* a vertical cylinder in isometric: an ellipse foot, a wall, a lit ellipse top */
  function cylinder(I, cx, cy, r, z, h, colour) { const c0 = I.p(cx, cy, z), c1 = I.p(cx, cy, z + h), rx = r * 48 * 0.72, ry = rx * 0.5; const ctx = I.ctx; ctx.fillStyle = NW.shade(colour, -0.2); ctx.beginPath(); ctx.ellipse(c0[0], c0[1], rx, ry, 0, 0, Math.PI); ctx.lineTo(c1[0] - rx, c1[1]); ctx.ellipse(c1[0], c1[1], rx, ry, 0, Math.PI, 0, true); ctx.closePath(); ctx.fill(); const g = ctx.createLinearGradient(c1[0] - rx, 0, c1[0] + rx, 0); g.addColorStop(0, NW.shade(colour, -0.05)); g.addColorStop(0.55, NW.shade(colour, -0.4)); g.addColorStop(1, NW.shade(colour, -0.15)); ctx.fillStyle = g; ctx.beginPath(); ctx.moveTo(c0[0] - rx, c0[1]); ctx.lineTo(c1[0] - rx, c1[1]); ctx.lineTo(c1[0] + rx, c1[1]); ctx.lineTo(c0[0] + rx, c0[1]); ctx.closePath(); ctx.fill(); ctx.fillStyle = NW.shade(colour, 0.2); ctx.beginPath(); ctx.ellipse(c1[0], c1[1], rx, ry, 0, 0, Math.PI * 2); ctx.fill(); return { top: c1, rx, ry }; }
  function dome(I, cx, cy, z, rx, colour) { const c = I.p(cx, cy, z); const ctx = I.ctx; const g = ctx.createRadialGradient(c[0] - rx * 0.35, c[1] - rx * 0.7, 2, c[0], c[1], rx * 1.1); g.addColorStop(0, NW.shade(colour, 0.35)); g.addColorStop(1, NW.shade(colour, -0.3)); ctx.fillStyle = g; ctx.beginPath(); ctx.ellipse(c[0], c[1], rx, rx * 0.85, 0, Math.PI, 0); ctx.closePath(); ctx.fill(); return c; }
  /* the home: from a variant, in the terrain's palette, with the kind's one detail */
  function house(I, gx, gy, vv, kind, now) {
    const has = f => vv.f.indexOf(' ' + f + ' ') >= 0; const era = vv.era | 0;
    const w = vv.w, d = vv.d, ox = gx + 0.5 - w / 2 + (PLACE.dx || 0), oy = PLACE.side === 'south' ? gy + 0.65 - d : PLACE.side === 'north' ? gy + 0.05 : gy + 0.5 - d / 2, wall = wallOf(MAT[vv.wall]()), tex = TEX[vv.wall];
    const fh = vv.fh, H = vv.fl * fh, lift = (vv.lift || 0) + (STY.stilts && era <= 2 ? 10 : 0), roofC = vv.roof === 'flat' ? (ROOF[era] || '#9aa3b0') : roofOf2(era >= 3 ? ROOF[era] : (era === 1 ? STY.roof1 : STY.roof2)), band = bandOf();
    const ctx = I.ctx; let b = null, top = lift + H;
    if (has('stem') || (STY.stilts && era <= 2 && lift)) { if (has('stem')) { I.box(ox + w / 2 - 0.12, oy + d / 2 - 0.12, 0.24, 0.24, lift, '#c9d2dc', 0, { noShadow: true }); const s = I.p(ox + w / 2, oy + d / 2); ctx.fillStyle = 'rgba(20,40,30,.2)'; ctx.beginPath(); ctx.ellipse(s[0], s[1], w * 20, w * 10, 0, 0, Math.PI * 2); ctx.fill(); } else stiltsOf(I, ox, oy, w, d, lift); }
    if (vv.base) I.box(ox - 0.06, oy - 0.06, w + 0.12, d + 0.12, 6, '#b3ada3', lift, { tex: 'stone' });
    const z0 = lift + (vv.base ? 6 : 0);
    if (has('cylinder')) { const r = Math.min(w, d) / 2; const cy = cylinder(I, ox + w / 2, oy + d / 2, r, z0, H, wall); for (let f = 0; f < vv.fl; f++) { const c = I.p(ox + w / 2, oy + d / 2, z0 + f * fh + fh * 0.35); ctx.strokeStyle = (N + f) % 3 ? 'rgba(255,240,200,.75)' : 'rgba(23,32,51,.45)'; ctx.lineWidth = fh * 0.3; ctx.beginPath(); ctx.ellipse(c[0], c[1], cy.rx * 0.98, cy.ry * 0.98, 0, 0.15, Math.PI - 0.15); ctx.stroke(); } b = { D: I.p(ox, oy + d, z0), C: I.p(ox + w, oy + d, z0), B: I.p(ox + w, oy, z0) }; }   /* a window band on every floor */
    else if (has('twin')) { const g = 0.12, sw = (w - g) / 2; const b1 = I.box(ox, oy, sw, d, H, wall, z0, { tex }); b = I.box(ox + sw + g, oy, sw, d, H, wall, z0, { tex }); if (has('skybridge')) I.box(ox + sw - 0.02, oy + d * 0.3, g + 0.04, d * 0.4, 8, '#dfe5ee', z0 + H * 0.6, { noShadow: true, tex: 'glass' }); [b1, b].forEach(bb => { for (let r = 0; r < vv.fl; r++) I.win(bb.D, bb.C, 0.2, 7 + r * fh, 0.6, fh * 0.45, (N + r) % 3 !== 0); }); }
    else if (has('steps')) { const n = Math.min(4, vv.fl); let z = z0; for (let i = 0; i < n; i++) { const inset = i * 0.12, fl = Math.ceil(vv.fl / n); const bb = I.box(ox + inset, oy + inset, w - inset * 2, d - inset * 2, fl * fh, wall, z, { tex, noShadow: i > 0 }); for (let r = 0; r < fl; r++) [0.15, 0.5, 0.85].forEach(u => I.win(bb.D, bb.C, u, 7 + r * fh, 0.18, fh * 0.45, (N + r + i) % 3 !== 0)); if (i < n - 1) { I.flatRoof(ox + inset, oy + inset, w - inset * 2, d - inset * 2, z + fl * fh, roofC); if (has('garden') || has('balcony')) I.blob(I.p(ox + inset + 0.15, oy + inset + 0.15, z + fl * fh + 5)[0], I.p(ox + inset + 0.15, oy + inset + 0.15, z + fl * fh + 5)[1], 4, '#5cc464', 0.7); } z += fl * fh; b = bb; } top = z; }
    else { b = I.box(ox, oy, w, d, H, wall, z0, { tex }); if (vv.core) { const [cw, cf, cfh] = vv.core; const cb = I.box(ox + (w - cw) / 2, oy + (d - cw) / 2, cw, cw, cf * cfh, wall, z0 + H, { tex, noShadow: true }); for (let r = 0; r < cf; r++) [0.2, 0.6].forEach(u => I.win(cb.D, cb.C, u, 6 + r * cfh, 0.22, cfh * 0.45, (N + r) % 2 === 0)); I.flatRoof(ox + (w - cw) / 2, oy + (d - cw) / 2, cw, cw, z0 + H + cf * cfh, roofC); top = z0 + H + cf * cfh; } }
    /* windows and the door on the near faces; arches where the variant has them */
    if (b && !has('twin') && !has('steps') && !has('cylinder')) { const cols = w >= 1.3 ? [0.1, 0.36, 0.62] : w >= 1.1 ? [0.12, 0.45] : [0.2]; const side = d >= 1.2 ? [0.25, 0.6] : [0.35];
      for (let r = 0; r < vv.fl; r++) { const y = 7 + r * fh, hh = fh * 0.45; cols.forEach((u, i) => { if (r === 0 && u > 0.55 && !has('shopfront')) return; I.win(b.D, b.C, u, y, 0.16, hh, (N + r + i) % 3 !== 0); if (has('arch')) { const a = I.up(I.P(b.D, b.C, u + 0.08), y + hh); ctx.fillStyle = '#e6f1fb'; ctx.beginPath(); ctx.ellipse(a[0], a[1], 5, 3, 0, Math.PI, 0); ctx.fill(); } }); side.forEach((u, i) => I.win(b.C, b.B, u, y, 0.2, hh, (N + r + i) % 2 === 0)); }
      if (has('shopfront')) { const a = I.P(b.D, b.C, 0.08), c = I.P(b.D, b.C, 0.92); I.poly([a, c, I.up(c, fh * 0.7), I.up(a, fh * 0.7)], '#dff1ff'); I.line(I.P(a, c, 0.5), I.up(I.P(a, c, 0.5), fh * 0.7), '#e6e9ef', 1.5); } else if (vv.roof !== 'tent') I.door(b.D, b.C, has('columns') ? 0.42 : 0.7, 0.18, Math.min(22, fh * 0.85), era >= 4 ? '#172033' : '#4a2b17');
      if (has('awning')) { const a = I.P(b.D, b.C, has('shopfront') ? 0.05 : 0.6), c = I.P(b.D, b.C, has('shopfront') ? 0.95 : 0.85), hz = fh * 0.78; I.poly([I.up(a, hz), I.up(c, hz), [I.up(c, hz)[0] + 5, I.up(c, hz)[1] + 6], [I.up(a, hz)[0] + 5, I.up(a, hz)[1] + 6]], band); }
      if (has('loft')) { const a = I.P(b.D, b.C, 0.42), c = I.P(b.D, b.C, 0.58), hz = H - fh * 0.75; I.poly([I.up(a, hz), I.up(c, hz), I.up(c, hz + fh * 0.5), I.up(a, hz + fh * 0.5)], '#4a2b17'); }
      if (has('bay')) { const bb = I.box(ox + w * 0.12, oy + d, w * 0.3, 0.14, fh * 0.85, wall, z0, { noShadow: true, tex }); I.win(bb.D, bb.C, 0.2, 6, 0.6, fh * 0.45, true); }
      if (has('balcony')) for (let r = 1; r < Math.min(vv.fl, 3); r++) { const s = I.box(ox - 0.04, oy + d, w + 0.08, 0.14, 2.5, NW.shade(wall, -0.15), z0 + r * fh, { noShadow: true }); for (let u = 0; u <= 1.001; u += 0.2) I.line(I.P(s.D2, s.C2, u), I.up(I.P(s.D2, s.C2, u), 6), '#5a5a50', 1); I.line(I.up(s.D2, 6), I.up(s.C2, 6), '#5a5a50', 1.2); }
      if (has('escape')) { let a = I.P(b.C, b.B, 0.25), c = I.P(b.C, b.B, 0.55); for (let r = 1; r < vv.fl; r++) { const y = r * fh; I.line(I.up(a, y), I.up(c, y), '#3b4252', 1.2); I.line(I.up(r % 2 ? a : c, y), I.up(r % 2 ? c : a, y + fh * 0.9), '#3b4252', 1); } }
      if (has('columns')) [0.06, 0.3, 0.7, 0.94].forEach(u => I.box(ox + u * (w - 0.08), oy + d + 0.02, 0.08, 0.08, has('porch') || has('veranda') ? fh * 0.9 : H, '#f4f1e8', z0, { noShadow: true }));
      if (has('timber')) { [0.12, 0.38, 0.62, 0.88].forEach(u => I.line(I.P(b.D, b.C, u), I.up(I.P(b.D, b.C, u), H), STY.timber || '#5a3a1e', 1.5)); for (let r = 1; r <= vv.fl; r++) I.line(I.up(b.D, r * fh), I.up(b.C, r * fh), STY.timber || '#5a3a1e', 1.5); } }
    /* things beside the house */
    if (has('porch') || has('veranda')) { const pb = I.box(ox, oy + d, w, 0.3, 3, '#c9a06a', lift, { noShadow: true }); [0.08, 0.92].forEach(u => I.box(ox + u * (w - 0.06), oy + d + 0.24, 0.06, 0.06, fh * 0.85, '#8a6a3f', lift + 3, { noShadow: true })); I.poly([I.p(ox - 0.05, oy + d, lift + fh * 0.88 + 3), I.p(ox + w + 0.05, oy + d, lift + fh * 0.88 + 3), I.p(ox + w + 0.05, oy + d + 0.36, lift + fh * 0.72 + 3), I.p(ox - 0.05, oy + d + 0.36, lift + fh * 0.72 + 3)], NW.shade(roofC, -0.1)); void pb; }
    if (has('veranda')) { I.box(ox + w, oy, 0.3, d, 3, '#c9a06a', lift, { noShadow: true }); I.poly([I.p(ox + w, oy - 0.05, lift + fh * 0.88 + 3), I.p(ox + w, oy + d + 0.05, lift + fh * 0.88 + 3), I.p(ox + w + 0.36, oy + d + 0.05, lift + fh * 0.72 + 3), I.p(ox + w + 0.36, oy - 0.05, lift + fh * 0.72 + 3)], NW.shade(roofC, -0.2)); }
    if (has('leanto')) { const lb = I.box(ox + w, oy + 0.15, 0.32, d - 0.3, H * 0.55, wall, lift, { noShadow: true, tex }); I.poly([I.up(lb.D, H * 0.55), I.up(lb.C, H * 0.55), I.up(lb.B, H * 0.55), I.p(ox + w, oy + 0.15, lift + H * 0.8), I.p(ox + w, oy + d - 0.15, lift + H * 0.8)], NW.shade(roofC, -0.1)); }
    if (has('garage')) { const gb = I.box(ox + w, oy + d * 0.45, 0.42, d * 0.5, fh * 0.8, NW.shade(wall, -0.08), lift, { noShadow: true, tex }); const a = I.P(gb.D, gb.C, 0.15), c = I.P(gb.D, gb.C, 0.85); I.poly([a, c, I.up(c, fh * 0.6), I.up(a, fh * 0.6)], '#dfe5ee'); for (let y = 4; y < fh * 0.6; y += 5) I.line(I.up(a, y), I.up(c, y), 'rgba(0,0,0,.15)', 1); I.flatRoof(ox + w, oy + d * 0.45, 0.42, d * 0.5, lift + fh * 0.8, roofC); }
    if (has('tower')) { const th = H + fh * 1.1; I.box(ox + w - 0.42, oy - 0.04, 0.42, 0.42, th, wall, lift, { noShadow: true, tex }); I.roof(ox + w - 0.42, oy - 0.04, 0.42, 0.42, lift + th, fh * 0.9, roofC, 0.08); }
    if (has('fence')) I.fence(gx - 0.35, gy + 1.35, gx + 1.35, gy + 1.35, 10);
    if (has('well') && B.CIV.well) B.CIV.well(I, gx + 1.05, gy - 0.35);
    /* the roof */
    const rz = top;
    if (has('cylinder')) { if (vv.roof === 'dome' || has('dome')) dome(I, ox + w / 2, oy + d / 2, rz, Math.min(w, d) * 48 * 0.36, wall); }
    else if ((vv.roof === 'gable' || vv.roof === 'hip') && era <= 2 && STY.roof !== 'gable') { roofOf(I, ox, oy, w, d, rz, fh * 0.85, roofC, wall); if (STY.roof === 'flat') top = rz + 4; }   /* the terrain's own way: flat in the desert, steep in the snow, thatch on the island, tiered in the garden */
    else if (vv.roof === 'gable') I.roof(ox, oy, w, d, rz, fh * 0.85, roofC);
    else if (vv.roof === 'hip') I.roof(ox, oy, w, d, rz, fh * 0.65, roofC, 0.1);
    else if (vv.roof === 'steep') I.roof(ox, oy, w, d, rz, fh * 1.5, roofC);
    else if (vv.roof === 'round') { I.roof(ox, oy, w, d, rz, fh * 0.5, NW.shade(roofC, 0.05), 0.12); }
    else if (vv.roof === 'mansard') { const mb = I.box(ox + 0.05, oy + 0.05, w - 0.1, d - 0.1, fh * 0.7, NW.shade(roofC, -0.25), rz, { noShadow: true }); if (has('dormer')) [0.25, 0.65].forEach(u => I.win(mb.D, mb.C, u, 5, 0.14, fh * 0.35, (N + Math.round(u * 10)) % 2 === 0)); I.flatRoof(ox + 0.12, oy + 0.12, w - 0.24, d - 0.24, rz + fh * 0.7, NW.shade(roofC, -0.1)); top = rz + fh * 0.7 + 4; }
    else if (vv.roof === 'sawtooth') { const n = 3; for (let i = 0; i < n; i++) I.roof(ox + i * w / n, oy, w / n, d, rz, fh * 0.55, i % 2 ? roofC : NW.shade(roofC, -0.12), 0.02); }
    else if (vv.roof === 'dome') { if (!has('cylinder')) { if (!has('twin')) I.flatRoof(ox, oy, w, d, rz, NW.shade(wall, -0.05)); const rx = Math.min(w, d) * 48 * (has('twin') ? 0.2 : 0.34); if (has('twin')) { dome(I, ox + w * 0.25, oy + d / 2, rz, rx, wall); dome(I, ox + w * 0.75, oy + d / 2, rz, rx, wall); } else dome(I, ox + w / 2, oy + d / 2, rz + 4, rx, wall); top = rz + 4 + rx * 0.85; } }
    else if (vv.roof === 'flat') { if (!has('steps') && !has('cylinder')) { I.flatRoof(ox, oy, w, d, rz, roofC); top = rz + 4; } }
    if (has('setback') && !has('steps')) { const sb = I.box(ox + w * 0.2, oy + d * 0.2, w * 0.6, d * 0.6, fh * 1.4, wall, top, { noShadow: true, tex }); [0.3, 0.7].forEach(u => I.win(sb.D, sb.C, u, 6, 0.2, fh * 0.5, (N + 1) % 2 === 0)); I.flatRoof(ox + w * 0.2, oy + d * 0.2, w * 0.6, d * 0.6, top + fh * 1.4, roofC); top += fh * 1.4 + 4; }
    if (has('dormer') && vv.roof !== 'mansard') { const db = I.box(ox + w * 0.32, oy + d * 0.55, 0.3, 0.3, 9, wall, rz + 4, { noShadow: true }); I.win(db.D, db.C, 0.2, 2, 0.6, 6, (N % 2) === 0); I.roof(ox + w * 0.32, oy + d * 0.55, 0.3, 0.3, rz + 13, 6, roofC, 0.04); }
    if (has('chimney')) I.chimney(ox + w * 0.75, oy + 0.15, top + (vv.roof === 'flat' ? 0 : fh * 0.4), '#9c5a3a');
    if (has('stack')) { I.chimney(ox + w * 0.8, oy + 0.1, top + 8, '#6b7280'); smokeAt(I, ox + w * 0.86, oy + 0.16, top + 30, now); }
    if (has('garden')) [[0.25, 0.3, '#5cc464'], [0.6, 0.55, '#3fa66b'], [0.4, 0.75, '#7fc55a']].forEach(o => { const q = I.p(ox + w * o[0], oy + d * o[1], top + 2); I.blob(q[0], q[1], 4 + w * 2, o[2], 0.7); });
    if (has('solar')) { const q0 = I.p(ox + 0.1, oy + 0.1, top + 1), q1 = I.p(ox + w - 0.1, oy + 0.1, top + 1), q2 = I.p(ox + w - 0.1, oy + d - 0.1, top + 1), q3 = I.p(ox + 0.1, oy + d - 0.1, top + 1); I.poly([q0, q1, q2, q3], '#1f3a6b', 'rgba(255,255,255,.4)', 1); for (let t = 0.25; t < 1; t += 0.25) I.line(I.P(q0, q3, t), I.P(q1, q2, t), 'rgba(255,255,255,.35)', 1); }
    if (has('tank')) { cylinder(I, ox + w * 0.75, oy + d * 0.3, 0.12, top, 10, '#8a8f98'); }
    if (has('helipad')) { const c = I.p(ox + w / 2, oy + d / 2, top + 1); ctx.strokeStyle = '#ffc531'; ctx.lineWidth = 1.5; ctx.beginPath(); ctx.ellipse(c[0], c[1], w * 14, w * 7, 0, 0, Math.PI * 2); ctx.stroke(); ctx.fillStyle = '#ffc531'; ctx.font = '800 9px Baloo 2, system-ui, sans-serif'; ctx.textAlign = 'center'; ctx.fillText('H', c[0], c[1] + 3); ctx.textAlign = 'left'; }
    if (has('ring')) { const q0 = I.p(ox + w * 0.3, oy + d * 0.3, top + 0.5), q1 = I.p(ox + w * 0.7, oy + d * 0.3, top + 0.5), q2 = I.p(ox + w * 0.7, oy + d * 0.7, top + 0.5), q3 = I.p(ox + w * 0.3, oy + d * 0.7, top + 0.5); I.poly([q0, q1, q2, q3], has('glow') ? 'rgba(79,240,255,.35)' : '#7fc55a'); }
    if (has('crown')) { I.box(ox - 0.03, oy - 0.03, w + 0.06, d + 0.06, 6, '#e6e9ef', top, { noShadow: true, top: 0.3 }); const c = I.p(ox + w / 2, oy + d / 2, top + 4); if (has('glow')) I.lights.push({ x: c[0], y: c[1], r: 30, c: '120,220,255', k: 0.6 }); top += 6; }
    if (has('spire')) { const c = I.p(ox + w / 2, oy + d / 2, top); I.line(c, [c[0], c[1] - fh * 1.2], '#e6e9ef', 2); I.blob(c[0], c[1] - fh * 1.2 - 2, 2.5, band); }
    if (has('antenna')) { const c = I.p(ox + w * 0.7, oy + d * 0.3, top); I.line(c, [c[0], c[1] - 18], '#8a95a3', 1.5); I.blob(c[0], c[1] - 19, 1.8, Math.floor(now / 500) % 2 ? '#ff4d4d' : '#ffb3b3'); }
    if (has('glow')) { const c = I.p(ox + w / 2, oy + d / 2, z0 + H * 0.5); I.lights.push({ x: c[0], y: c[1], r: 26 + H * 0.15, c: '120,220,255', k: 0.5 }); if (b) { ctx.strokeStyle = 'rgba(79,240,255,.7)'; ctx.lineWidth = 1.5; for (let r = 1; r < vv.fl; r++) { ctx.beginPath(); const a = I.up(b.D, r * fh - 2), c2 = I.up(b.C, r * fh - 2); ctx.moveTo(a[0], a[1]); ctx.lineTo(c2[0], c2[1]); ctx.stroke(); } } }
    if (b) detail(I, b, gx, gy, top, kind, now);
  }
  /* the campground: canvas, poles and rope; six tents, each its own shape */
  function tent(I, gx, gy, vv, kind, now) {
    const c = I.p(gx + 0.5, gy + 0.5), t = accent(kind), ctx = I.ctx, cv = '#e9e4d6', dark = '#cfc7aa', w = vv.w * 20, h = vv.fh; ctx.fillStyle = 'rgba(20,40,30,.22)'; ctx.beginPath(); ctx.ellipse(c[0] + 2, c[1] + 2, w + 2, w * 0.45, 0, 0, Math.PI * 2); ctx.fill();
    if (vv.roof === 'tent') { I.poly([[c[0] - w, c[1] + 3], [c[0] + w, c[1] + 3], [c[0], c[1] - h - 4]], cv); I.poly([[c[0], c[1] + 3], [c[0] + w, c[1] + 3], [c[0], c[1] - h - 4]], dark); I.poly([[c[0] - 5, c[1] + 3], [c[0] + 5, c[1] + 3], [c[0], c[1] - 12]], '#6b4a2b'); ctx.fillStyle = t; ctx.fillRect(c[0] - w + 1, c[1], w * 2 - 2, 3); I.poly([[c[0] - w - 6, c[1] + 6], [c[0] + 2, c[1] + 6], [c[0], c[1] - 2], [c[0] - w, c[1] - 2]], 'rgba(233,228,214,.7)'); }
    else if (vv.roof === 'domeTent') { const g = ctx.createRadialGradient(c[0] - 6, c[1] - h, 2, c[0], c[1] - 4, w + 4); g.addColorStop(0, '#f4f1e8'); g.addColorStop(1, dark); ctx.fillStyle = g; ctx.beginPath(); ctx.ellipse(c[0], c[1] + 1, w, h, 0, Math.PI, 0); ctx.closePath(); ctx.fill(); ctx.strokeStyle = t; ctx.lineWidth = 1.5; ctx.beginPath(); ctx.moveTo(c[0] - w, c[1] + 1); ctx.quadraticCurveTo(c[0] - 2, c[1] - h - 4, c[0] + w * 0.6, c[1] + 1); ctx.stroke(); I.poly([[c[0] - 4, c[1] + 1], [c[0] + 4, c[1] + 1], [c[0], c[1] - 9]], '#4a3a2a'); }
    else if (vv.roof === 'cone') { I.poly([[c[0] - w * 0.9, c[1] + 3], [c[0] + w * 0.9, c[1] + 3], [c[0], c[1] - h]], cv); I.poly([[c[0], c[1] + 3], [c[0] + w * 0.9, c[1] + 3], [c[0], c[1] - h]], dark); [[-3, 1], [0, 0], [3, 1]].forEach(o => I.line([c[0] + o[0] * 2, c[1] - h - 2], [c[0] + o[0] * 3.5, c[1] - h - 10 - o[1]], '#6b4a2b', 1.5)); ctx.fillStyle = t; ctx.beginPath(); ctx.moveTo(c[0] - w * 0.5, c[1] + 2); ctx.lineTo(c[0] + w * 0.5, c[1] + 2); ctx.lineTo(c[0] + w * 0.35, c[1] - 3); ctx.lineTo(c[0] - w * 0.35, c[1] - 3); ctx.closePath(); ctx.fill(); I.poly([[c[0] - 4, c[1] + 3], [c[0] + 4, c[1] + 3], [c[0], c[1] - 11]], '#4a3a2a'); if (vv.f.indexOf('smoke') >= 0) I.smoke(c[0], c[1] - h - 4, now); }
    else if (vv.roof === 'yurt') { const r = cylinder(I, gx + 0.5, gy + 0.5, vv.w / 2, 0, h, '#e9e4d6'); ctx.fillStyle = dark; ctx.beginPath(); ctx.ellipse(r.top[0], r.top[1], r.rx, r.ry, 0, 0, Math.PI * 2); ctx.fill(); I.poly([[r.top[0] - r.rx, r.top[1]], [r.top[0] + r.rx, r.top[1]], [r.top[0], r.top[1] - 12]], cv); ctx.strokeStyle = t; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(c[0] - r.rx + 1, c[1] - 4); ctx.lineTo(c[0] + r.rx - 1, c[1] - 4); ctx.stroke(); I.poly([[c[0] - 4, c[1] + 1], [c[0] + 4, c[1] + 1], [c[0] + 4, c[1] - 9], [c[0] - 4, c[1] - 9]], '#4a3a2a'); I.chimney(gx + 0.62, gy + 0.3, h + 4, '#6b7280'); }
    else if (vv.roof === 'leanTent') { I.poly([[c[0] - w, c[1] + 3], [c[0] + w * 0.4, c[1] + 3], [c[0] + w * 0.4, c[1] - h], [c[0] - w, c[1] - 6]], cv); I.poly([[c[0] + w * 0.4, c[1] + 3], [c[0] + w, c[1] - 2], [c[0] + w, c[1] - h - 4], [c[0] + w * 0.4, c[1] - h]], dark); [[-w, -6], [w * 0.4, -h]].forEach(o => I.line([c[0] + o[0], c[1] + 3], [c[0] + o[0], c[1] + o[1]], '#6b4a2b', 2)); I.chimney(gx + 0.7, gy + 0.2, h - 6, '#6b7280'); const q = I.p(gx + 0.76, gy + 0.26, h + 12); I.smoke(q[0], q[1], now); }
    else if (vv.roof === 'pups') { [-w * 0.5, w * 0.5].forEach(o => { I.poly([[c[0] + o - 11, c[1] + 3], [c[0] + o + 11, c[1] + 3], [c[0] + o, c[1] - h - 2]], cv); I.poly([[c[0] + o, c[1] + 3], [c[0] + o + 11, c[1] + 3], [c[0] + o, c[1] - h - 2]], dark); I.poly([[c[0] + o - 3, c[1] + 3], [c[0] + o + 3, c[1] + 3], [c[0] + o, c[1] - 6]], '#6b4a2b'); }); ctx.fillStyle = t; ctx.fillRect(c[0] - w, c[1] + 1, w * 2, 2); I.fence(gx - 0.2, gy + 1.25, gx + 1.2, gy + 1.25, 6); }
    else { /* a tarp fly on two poles, bedrolls under it */ [[-w, 0], [w, 0]].forEach(o => I.line([c[0] + o[0], c[1] + 4], [c[0] + o[0], c[1] - h - 6], '#6b4a2b', 2)); I.poly([[c[0] - w - 4, c[1] - h - 6], [c[0] + w + 4, c[1] - h - 6], [c[0] + w + 8, c[1] - h + 4], [c[0] - w - 8, c[1] - h + 4]], '#7a8f3a'); I.poly([[c[0] - w - 8, c[1] - h + 4], [c[0] + w + 8, c[1] - h + 4], [c[0] + w + 8, c[1] - h + 7], [c[0] - w - 8, c[1] - h + 7]], '#5f7a3a'); [[-8, 0], [6, 2]].forEach((o, i) => I.roundRect(c[0] + o[0] - 8, c[1] + o[1] - 4, 16, 6, 3, i ? t : '#3b6fb5')); }
    if (vv.f.indexOf('fence') >= 0 && vv.roof !== 'pups') I.fence(gx - 0.3, gy + 1.3, gx + 1.3, gy + 1.3, 8);
    if (vv.f.indexOf('porch') >= 0) I.poly([[c[0] - w * 0.6, c[1] + 4], [c[0] + w * 0.6, c[1] + 4], [c[0] + w * 0.6, c[1] + 8], [c[0] - w * 0.6, c[1] + 8]], '#8a6a3f');
    if (vv.f.indexOf('awning') >= 0) { const q = I.p(gx + 1.05, gy + 0.6); for (let i = 0; i < 5; i++) { ctx.fillStyle = i % 2 ? '#8a5a3a' : '#6b4a2b'; ctx.fillRect(q[0] - 6 + (i % 3) * 4, q[1] - 4 - Math.floor(i / 3) * 3.5, 3.5, 3); } }
  }
  const ERA_HOME = [0, 1, 2, 3, 4, 5, 6].map(era => function (I, gx, gy, k, now, kind) { const vv = pick(era); vv.era = era; if (era === 0) tent(I, gx, gy, vv, kind, now); else house(I, gx, gy, vv, kind, now); });
  const TOP = [40, 70, 80, 120, 230, 230, 260];   /* how tall an era's tallest home is, for the reveal */
  /* ---- the building site: a real one. Packed earth, tape on the posts, the stock for the job, scaffolding that climbs with the steps, a crane from the city on ---- */
  function siteGround(I, gx, gy) { const ctx = I.ctx, pts = [I.p(gx - 0.45, gy - 0.45), I.p(gx + 1.45, gy - 0.45), I.p(gx + 1.45, gy + 1.45), I.p(gx - 0.45, gy + 1.45)], c = I.p(gx + 0.5, gy + 0.5), g = ctx.createRadialGradient(c[0], c[1], 4, c[0], c[1], NW.TW * 1.3);
    g.addColorStop(0, '#b9976a'); g.addColorStop(0.7, '#a8845a'); g.addColorStop(1, 'rgba(150,118,80,.0)'); I.poly(pts, g);
    ctx.strokeStyle = 'rgba(90,64,36,.35)'; ctx.lineWidth = 1.4; [[0.2, 0.75], [0.35, 0.9]].forEach(([u, v]) => { const a = I.p(gx - 0.4, gy + u), b = I.p(gx + 1.4, gy + v); ctx.beginPath(); ctx.moveTo(a[0], a[1]); ctx.quadraticCurveTo((a[0] + b[0]) / 2, (a[1] + b[1]) / 2 - 6, b[0], b[1]); ctx.stroke(); });   /* the tyre tracks */
    for (let i = 0; i < 9; i++) { const q = I.p(gx - 0.3 + NW.State.hash(gx + i, gy) * 1.6, gy - 0.3 + NW.State.hash(gx, gy + i * 3) * 1.6); ctx.fillStyle = 'rgba(110,82,50,.5)'; ctx.beginPath(); ctx.ellipse(q[0], q[1], 1.6, 0.9, 0, 0, Math.PI * 2); ctx.fill(); } }
  function siteTape(I, gx, gy) { const ctx = I.ctx, corners = [[-0.45, -0.45], [1.45, -0.45], [1.45, 1.45], [-0.45, 1.45]].map(o => I.p(gx + o[0], gy + o[1]));
    [[3, 0], [0, 1], [1, 2]].forEach(([i, j]) => { const a = corners[i], b = corners[j]; ctx.lineWidth = 1.6; ctx.setLineDash([4, 4]); ctx.strokeStyle = '#ffc531'; ctx.beginPath(); ctx.moveTo(a[0], a[1] - 7); ctx.lineTo(b[0], b[1] - 7); ctx.stroke(); ctx.lineDashOffset = 4; ctx.strokeStyle = '#2a2230'; ctx.stroke(); ctx.lineDashOffset = 0; ctx.setLineDash([]); });
    corners.forEach(q => { ctx.fillStyle = '#f4f1e8'; ctx.fillRect(q[0] - 1, q[1] - 10, 2, 10); ctx.fillStyle = '#ff7a2a'; ctx.beginPath(); ctx.moveTo(q[0] - 3, q[1] - 10); ctx.lineTo(q[0], q[1] - 15); ctx.lineTo(q[0] + 3, q[1] - 10); ctx.fill(); }); }
  function siteStock(I, gx, gy, era) {
    /* lumber on the left; bricks from the town; steel and a mixer from the city */
    for (let i = 0; i < 3; i++) I.box(gx - 0.42 + i * 0.02, gy + 1.02, 0.5, 0.26, 3, i % 2 ? '#c9a06a' : '#b8874f', i * 3, { noShadow: i > 0, top: 0.2 });
    if (era >= 2) { I.box(gx + 1.12, gy + 1.08, 0.3, 0.3, 2, '#8a6a3f', 0, { top: 0.1 }); I.box(gx + 1.14, gy + 1.1, 0.26, 0.26, 9, '#b8553f', 2, { noShadow: true, tex: 'brick' }); }
    if (era >= 3) { [0, 1, 2].forEach(i => I.box(gx + 1.12 + i * 0.02, gy - 0.42, 0.12, 0.6, 2.5, '#6b7280', i * 2.5, { noShadow: i > 0, top: 0.15 })); const m = I.p(gx - 0.35, gy - 0.3); I.box(gx - 0.45, gy - 0.4, 0.3, 0.3, 5, '#e8552f', 0, { top: 0.1 }); I.ctx.fillStyle = '#f2b42a'; I.ctx.beginPath(); I.ctx.ellipse(m[0] + 2, m[1] - 11, 5, 4, -0.5, 0, Math.PI * 2); I.ctx.fill(); }
  }
  function scaffold(I, gx, gy, rise) { const wood = '#b58a5a', plank = '#c9a06a', ctx = I.ctx, lv = Math.max(1, Math.floor(rise / 14));
    [[-0.2, -0.2], [1.2, -0.2], [-0.2, 1.2], [1.2, 1.2], [0.5, 1.2], [1.2, 0.5]].forEach(o => { const q = I.p(gx + o[0], gy + o[1], 4); I.line(q, [q[0], q[1] - rise - 6], wood, 1.4); });
    for (let i = 1; i <= lv; i++) { const z = 4 + Math.min(rise, i * 14), a = I.p(gx - 0.22, gy + 1.22, z), b = I.p(gx + 1.22, gy + 1.22, z), c = I.p(gx + 1.22, gy - 0.22, z);
      I.poly([a, b, I.p(gx + 1.22, gy + 1.42, z), I.p(gx - 0.22, gy + 1.42, z)], plank); I.poly([b, c, I.p(gx + 1.42, gy - 0.22, z), I.p(gx + 1.42, gy + 1.22, z)], NW.shade(plank, -0.15));
      I.line(a, b, wood, 1.2); I.line(b, c, wood, 1.2); const a0 = I.p(gx - 0.22, gy + 1.22, z - 14), b0 = I.p(gx + 1.22, gy + 1.22, z - 14); ctx.globalAlpha = 0.6; I.line(a0, b, wood, 0.9); I.line(b0, I.p(gx + 1.22, gy - 0.22, z), wood, 0.9); ctx.globalAlpha = 1; }
    const top = I.p(gx + 1.22, gy + 1.22, rise + 4); I.ctx.setLineDash([2, 2]); I.line(I.p(gx - 0.22, gy + 1.22, rise + 4), top, 'rgba(255,255,255,.75)', 1); I.line(top, I.p(gx + 1.22, gy - 0.22, rise + 4), 'rgba(255,255,255,.75)', 1); I.ctx.setLineDash([]); }
  /* a tower crane: the mast, the jib turning slowly, the hook over the work */
  function crane(I, gx, gy, rise, now) { const ctx = I.ctx, base = I.p(gx + 1.8, gy - 0.6), H = Math.max(110, rise + 60), topY = base[1] - H, a = Math.sin(now / 5200) * 0.5 - 0.25, jl = 70, arm = [base[0] - Math.cos(a) * jl, topY + Math.sin(a) * jl * 0.35], back = [base[0] + Math.cos(a) * 26, topY - Math.sin(a) * 9];
    I.box(gx + 1.62, gy - 0.78, 0.36, 0.36, 5, '#8a95a6', 0, { top: 0.1 }); ctx.strokeStyle = '#f2b42a'; ctx.lineWidth = 1.2; for (let y = 0; y < H; y += 9) { ctx.beginPath(); ctx.moveTo(base[0] - 3, base[1] - y); ctx.lineTo(base[0] + 3, base[1] - y - 9); ctx.moveTo(base[0] + 3, base[1] - y); ctx.lineTo(base[0] - 3, base[1] - y - 9); ctx.stroke(); } I.line([base[0] - 3, base[1]], [base[0] - 3, topY], '#e0a020', 1.6); I.line([base[0] + 3, base[1]], [base[0] + 3, topY], '#e0a020', 1.6);
    I.line([base[0], topY - 12], arm, '#6b7280', 0.8); I.line([base[0], topY - 12], back, '#6b7280', 0.8); I.line(back, arm, '#f2b42a', 3); ctx.fillStyle = '#6b7280'; ctx.fillRect(back[0] - 4, back[1] - 2, 8, 7); ctx.fillStyle = '#2f7fd6'; ctx.fillRect(base[0] - 4, topY + 1, 8, 7);
    const hook = [arm[0] + 6, Math.min(base[1] - rise - 30, arm[1] + 40 + Math.sin(now / 900) * 4)]; I.line([arm[0] + 6, arm[1]], hook, '#3b4252', 0.8); ctx.fillStyle = '#c9a06a'; ctx.fillRect(hook[0] - 7, hook[1], 14, 3); }
  /* before cranes: a timber hoist, two legs, a pulley and a bucket going up and down */
  function hoist(I, gx, gy, rise, now) { const a = I.p(gx + 1.45, gy - 0.35), b = I.p(gx + 1.45, gy + 0.35), H = Math.max(50, rise + 24), top = [(a[0] + b[0]) / 2 - 10, Math.min(a[1], b[1]) - H]; I.line(a, top, '#8a6a3f', 2.2); I.line(b, top, '#8a6a3f', 2.2); I.line(top, [top[0] - 22, top[1] + 4], '#8a6a3f', 2); const y = top[1] + 10 + (Math.sin(now / 1400) * 0.5 + 0.5) * (H - 30); I.line([top[0] - 20, top[1] + 4], [top[0] - 20, y], '#3b3a44', 0.8); I.ctx.fillStyle = '#6b4a2b'; I.ctx.fillRect(top[0] - 23, y, 6, 5); I.ctx.fillStyle = '#9aa3b0'; I.ctx.beginPath(); I.ctx.arc(top[0] - 20, top[1] + 4, 2, 0, Math.PI * 2); I.ctx.fill(); }
  function dust(I, gx, gy, now) { const ctx = I.ctx; for (let i = 0; i < 4; i++) { const ph = (now / 2600 + i * 0.25) % 1, q = I.p(gx + 0.2 + i * 0.3, gy + 1.2); ctx.fillStyle = 'rgba(210,190,150,' + (0.35 * (1 - ph)) + ')'; ctx.beginPath(); ctx.arc(q[0] + ph * 10, q[1] - 2 - ph * 14, 2 + ph * 5, 0, Math.PI * 2); ctx.fill(); } }
  function drawStage(I, gx, gy, done, total, kind, era, k, now, custom) {
    const draw = custom || ((I2, x, y) => ERA_HOME[era](I2, x, y, 1, now, kind)); const n = Math.max(1, total | 0), frac = Math.min(done, n) / n, rise = frac * (custom ? 90 : TOP[era]) * (0.75 + 0.25 * k);
    if (done >= n) { draw(I, gx, gy); return 'Finished'; }
    siteGround(I, gx, gy); siteStock(I, gx, gy, era);
    if (done > 0) {
      /* the slab, then the building itself up to the height the steps have reached */
      I.box(gx - 0.2, gy - 0.2, 1.4, 1.4, 4, era >= 2 ? '#c9c2b0' : '#8a6a3f', 0, { top: 0.1 });
      const base = I.p(gx + 0.5, gy + 1.5); I.ctx.save(); I.ctx.beginPath(); I.ctx.rect(base[0] - (custom ? 200 : 60), base[1] - 4 - rise, custom ? 400 : 120, rise + 8); I.ctx.clip(); draw(I, gx, gy); I.ctx.restore();
      scaffold(I, gx, gy, rise); if (era >= 3) crane(I, gx, gy, rise, now); else if (custom || era >= 1) hoist(I, gx, gy, rise, now); if (!NW.reduce) dust(I, gx, gy, now);
      I.puff(gx, gy, k);
    } else { const q = I.p(gx + 0.5, gy + 0.5); I.ctx.setLineDash([3, 3]); I.poly([I.p(gx - 0.1, gy - 0.1), I.p(gx + 1.1, gy - 0.1), I.p(gx + 1.1, gy + 1.1), I.p(gx - 0.1, gy + 1.1)], 'rgba(255,255,255,.14)', 'rgba(255,255,255,.85)', 1.2); I.ctx.setLineDash([]); I.ctx.fillStyle = '#2f7fd6'; I.ctx.fillRect(q[0] - 8, q[1] - 16, 16, 11); I.ctx.fillStyle = '#e6f1fb'; I.ctx.fillRect(q[0] - 6, q[1] - 14, 12, 7); I.line([q[0], q[1] - 5], [q[0], q[1] + 2], '#6b4a2b', 1.4); }   /* pegged out: the outline and a blueprint on a stake */
    siteTape(I, gx, gy);
    return done === 0 ? 'Pegged out' : 'Step ' + done + ' of ' + n + ' up';
  }
  /* the hospital, at hospital size: three wide, two deep, three storeys, the cross on the roof */
  B.CIV.library = function (I, gx, gy, now) { if (!B.modern) { B.library(I, gx, gy, 1, now, 3); I.label(gx + 0.5, gy + 1.7, 'Library', '', 8); return; } I.box(gx - 0.15, gy - 0.15, 2.1, 1.7, 4, '#d6d1c4', 0, { top: 0.1, tex: 'stone' }); const H = 62, b = I.box(gx, gy, 1.8, 1.4, H, '#6fa8d8', 4, { tex: 'glass' }); [20, 40].forEach(v => { I.line(I.up(b.D, v), I.up(b.C, v), 'rgba(255,255,255,.5)', 1.2); I.line(I.up(b.C, v), I.up(b.B, v), 'rgba(255,255,255,.3)', 1.2); }); for (let u = 0.06; u < 0.95; u += 0.1) I.win(b.D, b.C, u, 46, 0.06, 12, (Math.floor(u * 100) % 3) !== 0); const a = I.P(b.D, b.C, 0.4), c = I.P(b.D, b.C, 0.6); I.poly([a, c, I.up(c, 30), I.up(a, 30)], '#efe9dc'); I.flatRoof(gx, gy, 1.8, 1.4, H + 4, '#dfe5ee'); I.tree(gx + 1.95, gy + 1.1, 0.8); I.label(gx + 0.9, gy + 2.2, 'Library', '', 8); };
  B.CIV.hospital = function (I, gx, gy, now) { I.box(gx - 0.2, gy - 0.2, 3.4, 2.4, 4, '#cfd5df', 0, { top: 0.1 }); const H = 108, b = I.box(gx, gy, 3, 2, H, '#dfe9f2', 4, { tex: 'glass' }); [36, 72].forEach(v => I.line(I.up(b.D, v), I.up(b.C, v), 'rgba(255,255,255,.6)', 1.5)); for (let r = 0; r < 3; r++) for (let u = 0.06; u < 0.95; u += 0.12) { if (r === 0 && u > 0.38 && u < 0.6) continue; I.win(b.D, b.C, u, 12 + r * 34, 0.07, 18, ((r + Math.floor(u * 10)) % 3) !== 0); } for (let r = 0; r < 3; r++) [0.15, 0.45, 0.75].forEach(u => I.win(b.C, b.B, u, 12 + r * 34, 0.16, 18, r !== 1)); const a = I.P(b.D, b.C, 0.4), c = I.P(b.D, b.C, 0.6); I.poly([a, c, I.up(c, 20), I.up(a, 20)], '#9ad3ff'); I.poly([I.p(gx + 0.9, gy + 2.05, 24), I.p(gx + 2.1, gy + 2.05, 24), I.p(gx + 2.1, gy + 2.5, 20), I.p(gx + 0.9, gy + 2.5, 20)], '#e8352f'); I.flatRoof(gx, gy, 3, 2, H + 4, '#dfe5ee'); const s = I.p(gx + 1.5, gy + 1, H + 12); I.roundRect(s[0] - 9, s[1] - 9, 18, 18, 3, '#ffffff'); I.ctx.fillStyle = '#e8352f'; I.ctx.fillRect(s[0] - 2.5, s[1] - 7, 5, 14); I.ctx.fillRect(s[0] - 7, s[1] - 2.5, 14, 5); I.box(gx + 2.5, gy + 0.3, 0.3, 0.3, 10, '#dfe5ee', H + 4, { noShadow: true }); I.label(gx + 1.5, gy + 2.9, 'Hospital', '', 9); };
  B.CIV.datacentre = function (I, gx, gy, now) { B.datacentre(I, gx, gy, 1, now, 3); I.label(gx + 0.6, gy + 1.7, 'Data Centre', 'what keeps the city running', 8); };
  const setN = (n, place) => { N = n | 0; PLACE = place || {}; };
  const setLive = v => { live = !!v; if (!live) smokes = []; };
  const takeSmokes = () => { const s = smokes; smokes = []; return s; };
  NW.Homes = { setTerrain, setN, setLive, takeSmokes, STYLES, PALETTE, ERA_HOME, VARIANTS, drawStage, KIND };
})();
