/* NextWorld · views: the panel itself
 * mount(root, host) builds the tabs inside root (an element or a shadow
 * root) and draws only the tab that is showing. The host supplies storage,
 * the theme, and what "open this project" means; nothing here touches the
 * page. Pip, the pineapple, sits under every scene and says the one next
 * thing. */
'use strict';
(function () {
  const { makeIso, B, clamp, lerp, reduce, SERIES, START_HERE, ABOUT, KIND_NAME, ICON, TW, TH } = NW;
  const S = NW.State, Land = NW.Land, HQ = NW.HQ, G = NW.Global, E = NW.Eras;
  const TABS = [['world', 'NextWorld'], ['avatar', 'Avatar'], ['base', 'My World'], ['build', 'My Build'], ['global', 'Globe']];

  const CSS = `
    :host, .nww { all: initial; }
    .nww { display: block; font: 14px/1.45 Nunito, "Segoe UI", system-ui, sans-serif; color: var(--nww-text, #f2f5fb); background: var(--nww-canvas, #172033); border-radius: 14px; overflow: hidden; --gold: var(--nww-accent, #ffc531); --ink: var(--nww-accent-text, #4a2b00); --dim: var(--nww-dim, #a7b2c9); --line: var(--nww-line, rgba(255,255,255,.12)); --card: var(--nww-surface, #1f2a42); --ok: #47d16c; --xp: #4fc3ff; --bar: var(--nww-bar, linear-gradient(180deg, #223052, #182339)); --tab-on: var(--nww-surface-alt, #fff); --tab-on-text: var(--nww-tab-text, #172033); }
    .nww * { box-sizing: border-box; } .nww button { font: inherit; cursor: pointer; } .nww button:focus-visible, .nww canvas:focus-visible { outline: 3px solid var(--gold); outline-offset: 2px; }
    .bar { display: flex; align-items: center; gap: 8px; padding: 10px 12px 8px; background: var(--bar); border-bottom: 1px solid var(--line); flex-wrap: wrap; }
    .brand { font: 800 16px/1 "Baloo 2", "Segoe UI", system-ui, sans-serif; color: var(--nww-text, #fff); white-space: nowrap; } .brand span { color: var(--gold); } .brand[hidden] { display: none; }
    .mode { margin-left: auto; font: 700 12px/1 "Baloo 2", system-ui, sans-serif; padding: 7px 11px; border: 1px solid var(--line); border-radius: 999px; background: rgba(0,0,0,.25); color: var(--dim); }
    .mode[data-on="dev"] { color: #0b3d1b; background: #8fe3a4; border-color: transparent; }
    .sparks { font: 800 12px/1 "Baloo 2", system-ui, sans-serif; padding: 7px 11px; border-radius: 999px; background: rgba(255,197,49,.16); color: var(--gold); border: 1px solid rgba(255,197,49,.35); white-space: nowrap; }
    .tabs { display: flex; gap: 3px; background: rgba(0,0,0,.25); border-radius: 12px; padding: 3px; width: 100%; }
    .tabs button { flex: 1; min-height: 36px; font: 700 13px/1.1 "Baloo 2", system-ui, sans-serif; padding: 8px 6px; border: 0; border-radius: 9px; background: transparent; color: var(--dim); white-space: nowrap; position: relative; }
    .tabs button[aria-selected="true"] { background: var(--tab-on); color: var(--tab-on-text); box-shadow: 0 2px 8px rgba(0,0,0,.35); }
    .tabs button[data-dot="1"]::after { content: ''; position: absolute; top: 5px; right: 8px; width: 7px; height: 7px; border-radius: 50%; background: var(--gold); }
    .view { padding: 12px 12px 16px; display: flex; flex-direction: column; gap: 12px; } .view[hidden] { display: none; }
    .scene { position: relative; border-radius: 12px; overflow: hidden; background: #8fd0ff; box-shadow: 0 10px 30px rgba(0,0,0,.4), inset 0 0 0 1px rgba(255,255,255,.15); line-height: 0; }
    .scene canvas { width: 100%; height: auto; display: block; touch-action: none; cursor: grab; }
    .badge { position: absolute; left: 8px; top: 8px; font: 800 12px/1.2 "Baloo 2", system-ui, sans-serif; color: #172033; background: rgba(255,255,255,.9); padding: 7px 11px; border-radius: 999px; border: 1px solid rgba(0,0,0,.12); } .badge small { font-weight: 700; color: #5b6478; margin-left: 6px; font-size: 11.5px; }
    .nav { position: absolute; right: 8px; bottom: 8px; display: flex; gap: 5px; flex-wrap: wrap; justify-content: flex-end; max-width: 75%; }
    .nav button, .devbar button { font: 700 11.5px/1 "Baloo 2", system-ui, sans-serif; padding: 7px 10px; border: 1px solid rgba(0,0,0,.12); border-radius: 999px; background: rgba(255,255,255,.9); color: #172033; } .nav button:hover, .devbar button:hover { background: #fff; } .devbar button[aria-pressed="true"] { background: var(--gold); color: var(--ink); }
    .hud { position: absolute; left: 8px; top: 8px; display: flex; align-items: center; gap: 7px; border: 0; padding: 0; background: transparent; cursor: pointer; text-align: left; } .hud:hover .who { border-color: var(--gold); }
    .shield { width: 36px; height: 40px; background: linear-gradient(180deg, #5db2ff, #1f6fd1); clip-path: polygon(50% 0, 100% 15%, 92% 72%, 50% 100%, 8% 72%, 0 15%); display: flex; align-items: center; justify-content: center; font: 800 15px/1 "Baloo 2", system-ui, sans-serif; color: #fff; }
    .who { background: rgba(255,255,255,.9); border: 1px solid rgba(0,0,0,.12); border-radius: 10px; padding: 5px 10px 6px; min-width: 120px; line-height: 1.3; } .who b { font: 800 12.5px/1.1 "Baloo 2", system-ui, sans-serif; color: #172033; display: block; } .who small { display: block; font-size: 11.5px; color: #4b5563; font-weight: 700; white-space: nowrap; margin-top: 1px; } .who small.next { color: #0f5fc6; }
    .pip { display: grid; grid-template-columns: 52px 1fr; gap: 10px; align-items: center; background: #fff; color: #172033; border-radius: 12px; padding: 8px 12px 8px 8px; box-shadow: 0 8px 24px rgba(0,0,0,.3); } .pip canvas { width: 52px; height: 60px; display: block; } .pip b { font: 800 14px/1.2 "Baloo 2", system-ui, sans-serif; display: block; margin-bottom: 1px; color: #0f5fc6; } .pip p { margin: 0; font-size: 13.5px; line-height: 1.4; } .pip button { grid-column: 2; justify-self: start; margin-top: 6px; font: 800 12px/1 "Baloo 2", system-ui, sans-serif; padding: 8px 12px; border: 0; border-radius: 9px; background: linear-gradient(180deg, #ffe27a, var(--gold) 55%, #ff9d1c); color: var(--ink); } .pip button[hidden] { display: none; }
    .cap { font-size: 12.5px; color: var(--dim); line-height: 1.45; } .cap b { color: var(--nww-text, #f2f5fb); }
    .tiles { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; } .tile { background: var(--card); border: 1px solid var(--line); border-radius: 12px; padding: 10px 12px; } .tile.wide { grid-column: 1 / -1; }
    .tile small { display: block; font-size: 11px; font-weight: 700; letter-spacing: .06em; text-transform: uppercase; color: var(--dim); } .tile b { font: 800 18px/1.1 "Baloo 2", system-ui, sans-serif; display: block; margin-top: 3px; color: var(--nww-text, #fff); } .tile span { font-size: 12.5px; color: var(--dim); display: block; margin-top: 2px; }
    .barx { height: 8px; border-radius: 6px; background: rgba(0,0,0,.35); margin-top: 8px; overflow: hidden; } .barx i { display: block; height: 100%; width: 0; background: linear-gradient(90deg, #2c8fe8, var(--xp)); border-radius: 6px; } .barx.gold i { background: linear-gradient(90deg, #ff9d1c, var(--gold)); }
    h3 { font: 800 14.5px/1.2 "Baloo 2", system-ui, sans-serif; margin: 6px 0 0; color: var(--nww-text, #fff); } h3 small { font: 600 12px/1 Nunito, system-ui, sans-serif; color: var(--dim); margin-left: 6px; }
    .fold { display: flex; align-items: center; gap: 8px; width: 100%; margin: 6px 0 0; padding: 8px 10px; border: 1px solid var(--line); border-radius: 10px; background: rgba(0,0,0,.18); color: var(--nww-text, #fff); font: 800 13.5px/1.2 "Baloo 2", system-ui, sans-serif; text-align: left; } .fold small { margin-left: auto; font: 700 12px/1 Nunito, system-ui, sans-serif; color: var(--dim); } .fold::before { content: '▸'; color: var(--dim); } .fold[aria-expanded="true"]::before { content: '▾'; }
    .list { display: flex; flex-direction: column; gap: 6px; } .list[hidden] { display: none; }
    .row { display: grid; grid-template-columns: 30px 1fr auto; gap: 10px; align-items: center; padding: 9px 11px; background: rgba(0,0,0,.22); border: 1px solid var(--line); border-radius: 10px; } .row.full { border-color: rgba(124,240,164,.5); } .row.going { border-color: rgba(255,197,49,.5); }
    .row i { width: 30px; height: 30px; border-radius: 8px; background: var(--card); display: flex; align-items: center; justify-content: center; font-style: normal; font-size: 15px; }
    .row .n { min-width: 0; } .row .n b { display: block; font-size: 13px; font-weight: 700; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; } .row .n small { display: block; font-size: 12px; color: var(--dim); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; margin-top: 1px; }
    .row .n .barx { height: 4px; margin-top: 5px; } .row .v { text-align: right; font: 800 12.5px/1.2 "Baloo 2", system-ui, sans-serif; white-space: nowrap; } .row .v small { display: block; font: 600 11.5px/1.2 Nunito, system-ui, sans-serif; color: var(--dim); }
    .row button, .board button { grid-column: 1 / -1; font: 800 12px/1 "Baloo 2", system-ui, sans-serif; padding: 8px; border: 0; border-radius: 8px; background: rgba(127,127,127,.18); color: var(--nww-text, #f2f5fb); } .row button:hover, .board button:hover { background: rgba(255,255,255,.14); }
    .row.quiet button { display: none; } .row.quiet:hover button, .row.quiet:focus-within button { display: block; }
    .board { display: flex; flex-direction: column; gap: 8px; background: #c9a06a; color: #3a2a12; border-radius: 12px; padding: 12px 14px; box-shadow: inset 0 0 0 4px #b58a5a; } .board h3 { color: #3a2a12; margin: 0; } .board p { margin: 0; font-size: 12.5px; }
    .pin { background: #fff8e0; border-radius: 6px; padding: 9px 11px; display: grid; grid-template-columns: 1fr auto; gap: 8px; align-items: center; box-shadow: 0 2px 0 rgba(0,0,0,.15); } .pin b { display: block; font-size: 13px; } .pin small { display: block; font-size: 12px; color: #6b5a3a; }
    .pin button { grid-column: auto; background: var(--gold); color: var(--ink); } .pin button:hover { background: #ffd35a; } .pin.met { background: #e6f7ea; }
    .btn { font: 700 13.5px/1.2 "Baloo 2", system-ui, sans-serif; min-height: 44px; padding: 10px 12px; border: 0; border-radius: 11px; background: var(--card); color: var(--nww-text, #f2f5fb); box-shadow: inset 0 -3px 0 rgba(0,0,0,.35); } .btn:hover { filter: brightness(1.1); } .btn[hidden] { display: none; }
    .btn.go { color: var(--ink); background: linear-gradient(180deg, #ffe27a, var(--gold) 55%, #ff9d1c); box-shadow: inset 0 -4px 0 rgba(0,0,0,.18); font-size: 15px; } .btn:disabled { opacity: .45; cursor: default; }
    .link { background: none; border: 0; padding: 4px 0; color: var(--xp); font: 700 12.5px/1.2 Nunito, system-ui, sans-serif; text-decoration: underline; align-self: flex-start; } .link[hidden] { display: none; }
    .steps { display: flex; flex-direction: column; gap: 2px; } .step { display: grid; grid-template-columns: 30px 1fr; gap: 10px; align-items: center; padding: 5px 4px; } .step i { width: 30px; height: 30px; border-radius: 50%; display: flex; align-items: center; justify-content: center; background: var(--card); border: 2px solid var(--line); font: 800 12px/1 "Baloo 2", system-ui, sans-serif; color: var(--dim); font-style: normal; }
    .step.done i { background: var(--ok); border-color: var(--ok); color: #fff; } .step.now i { border-color: var(--gold); color: var(--gold); } .step.done b { color: var(--dim); text-decoration: line-through; } .step b { font-size: 13px; font-weight: 700; }
    .card { background: #fff; color: #172033; border-radius: 12px; padding: 10px 12px; display: grid; grid-template-columns: 40px 1fr; gap: 10px; align-items: center; box-shadow: 0 10px 30px rgba(0,0,0,.4); } .card[hidden] { display: none; }
    .card .ic { width: 40px; height: 40px; border-radius: 10px; background: #eef2f8; display: flex; align-items: center; justify-content: center; font-size: 20px; } .card b { font: 800 13.5px/1.15 "Baloo 2", system-ui, sans-serif; display: block; } .card small { font-size: 12px; color: #5b6478; display: block; }
    .card .acts { grid-column: 1 / -1; display: grid; grid-template-columns: 1fr 1fr; gap: 6px; } .card .acts button { font: 800 12px/1 "Baloo 2", system-ui, sans-serif; padding: 9px 4px; border: 0; border-radius: 10px; background: #eef2f8; color: #172033; } .card .acts button.up { background: linear-gradient(180deg, #8fe3a4, #47d16c); color: #0b3d1b; } .card .acts button:disabled { opacity: .45; }
    .devtoggle { font: 700 12px/1 "Baloo 2", system-ui, sans-serif; margin: 8px 12px 0; padding: 6px 11px; border: 1px solid rgba(143,227,164,.4); border-radius: 999px; background: transparent; color: #8fe3a4; align-self: flex-start; } .devtoggle[hidden] { display: none; }
    .devbar { display: flex; flex-direction: column; gap: 6px; padding: 8px 12px 10px; background: rgba(143,227,164,.1); border-bottom: 1px solid rgba(143,227,164,.3); } .devbar[hidden] { display: none; }
    .devrow { display: flex; gap: 5px; flex-wrap: wrap; align-items: center; } .devrow > span { font: 800 11px/1 "Baloo 2", system-ui, sans-serif; color: #8fe3a4; text-transform: uppercase; letter-spacing: .06em; min-width: 46px; } .devrow input[type="range"] { width: 120px; accent-color: #ffc531; } .devrow input[type="number"] { width: 58px; font: 700 12px/1 "Baloo 2", system-ui, sans-serif; padding: 5px 6px; border: 1px solid var(--line); border-radius: 8px; background: var(--card); color: var(--nww-text, #fff); } .devrow .fps { font: 700 11px/1 "Baloo 2", system-ui, sans-serif; color: var(--dim); } .devbar textarea { width: 100%; height: 80px; font: 11px/1.3 ui-monospace, monospace; background: var(--card); color: var(--nww-text, #fff); border: 1px solid var(--line); border-radius: 8px; padding: 6px; } .devbar textarea[hidden] { display: none; }
    .about p { margin: 0; font-size: 13.5px; line-height: 1.5; } .about .tag { font: 800 22px/1.1 "Baloo 2", system-ui, sans-serif; color: #fff; } .about .mission { font-size: 15px; color: var(--gold); font-weight: 700; }
    .about a { color: var(--xp); font-weight: 700; text-decoration: none; } .about a:hover { text-decoration: underline; }
    .toast { position: absolute; right: 8px; top: 56px; font: 800 12.5px/1.25 "Baloo 2", system-ui, sans-serif; color: var(--ink); background: linear-gradient(180deg, #ffe27a, var(--gold)); padding: 8px 12px; border-radius: 10px; box-shadow: 0 6px 18px rgba(0,0,0,.35); opacity: 0; transform: translateY(-8px); transition: opacity .25s, transform .25s; pointer-events: none; } .toast.on { opacity: 1; transform: none; }
    .av { display: grid; grid-template-columns: 1fr; gap: 12px; } .av .opts { display: flex; flex-direction: column; gap: 10px; }
    .av .grp { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; } .av .grp > span { font: 700 11.5px/1 "Baloo 2", system-ui, sans-serif; color: var(--dim); min-width: 56px; text-transform: uppercase; letter-spacing: .05em; }
    .av .grp button { font: 700 12.5px/1 "Baloo 2", system-ui, sans-serif; min-height: 34px; padding: 8px 12px; border: 1px solid var(--line); border-radius: 999px; background: var(--card); color: var(--nww-text, #f2f5fb); } .av .grp button[aria-pressed="true"] { background: var(--gold); color: var(--ink); border-color: transparent; } .av .grp button[data-locked="1"] { color: var(--dim); border-style: dashed; }
    .av .sw { width: 34px; height: 34px; min-height: 34px; border-radius: 50%; border: 2px solid var(--line); padding: 0; } .av .sw[aria-pressed="true"] { border-color: var(--gold); box-shadow: 0 0 0 2px var(--gold); }
    .av input { font: inherit; padding: 9px 11px; border: 1px solid var(--line); border-radius: 10px; background: var(--card); color: var(--nww-text, #f2f5fb); min-width: 0; }
    .zoom { position: absolute; left: 8px; bottom: 8px; display: flex; gap: 5px; } .zoom button { width: 36px; height: 36px; font: 800 17px/1 "Baloo 2", system-ui, sans-serif; border: 1px solid rgba(0,0,0,.12); border-radius: 9px; background: rgba(255,255,255,.9); color: #172033; }
    .dash { position: absolute; left: 8px; right: 8px; top: 56px; bottom: 52px; overflow: auto; background: var(--nww-canvas, #172033); color: var(--nww-text, #f2f5fb); border: 1px solid var(--line); border-radius: 12px; padding: 12px; display: flex; flex-direction: column; gap: 8px; line-height: 1.4; box-shadow: 0 10px 30px rgba(0,0,0,.4); } .dash[hidden] { display: none; } .dash h3 { margin: 0 0 2px; }
    .levelup { position: absolute; left: 50%; bottom: 52px; transform: translateX(-50%); width: min(92%, 520px); background: rgba(255,255,255,.95); color: #172033; border-radius: 14px; padding: 12px 16px; text-align: center; box-shadow: 0 12px 34px rgba(0,0,0,.35); border: 2px solid var(--gold); } .levelup[hidden] { display: none; } .levelup small { display: block; font: 700 11.5px/1.2 "Baloo 2", system-ui, sans-serif; color: #8a5a3a; letter-spacing: .05em; text-transform: uppercase; } .levelup b { display: block; font: 800 20px/1.15 "Baloo 2", system-ui, sans-serif; margin: 2px 0 4px; } .levelup p { margin: 0; font-size: 13px; line-height: 1.45; }
    .prog { display: flex; flex-direction: column; gap: 5px; } .prog .barx { height: 12px; margin: 0; } .prog small { font-size: 12px; color: var(--dim); }
    .scene[hidden] { display: none; }
    @media (prefers-reduced-motion: reduce) { .toast { transition: none; } }
  `;

  const TERRAIN_ICON = { forest: '🌲', sandy: '🏜️', island: '🏝️', plains: '🌾', mountains: '🏔️', snow: '❄️', rain: '🌧️', zen: '🎋', savanna: '🦒' };
  /* the leaderboard NextWorld cannot see yet: sample builders, so the shape is there for the day NextWork publishes counts */
  const SAMPLE_BOARD = [['Maya', 'Lagos', 212], ['Ken', 'Osaka', 168], ['Priya', 'Pune', 154], ['Lucas', 'Lisbon', 121], ['Amara', 'Nairobi', 97]];
  const el = (tag, cls, text) => { const e = document.createElement(tag); if (cls) e.className = cls; if (text != null) e.textContent = text; return e; };
  const put = (parent, ...kids) => { kids.forEach(k => parent.appendChild(k)); return parent; };
  const setText = (node, text) => { if (node.textContent !== text) node.textContent = text; };
  const camTo = (gx, gy, H) => ({ x: (gx - gy) * TW / 2, y: 60 + (gx + gy) * TH / 2 - H / 2 - 10 });

  function mount(root, host) {
    const state = S.normalise(host.load()); const save = () => host.save(state);
    const wrap = el('div', 'nww'); const style = el('style'); style.textContent = CSS; put(root, style, wrap);
    /* the extension's own theme, when the host has one */
    function theme(p) { if (!p) return; const v = { canvas: p.canvas, surface: p.surfaceAlt || p.surface, 'surface-alt': p.surface, 'tab-text': p.textPrimary, text: p.textPrimary, dim: p.textSecondary, line: p.border, accent: p.accent, 'accent-text': p.accentText, bar: p.surface }; Object.keys(v).forEach(k => { if (v[k]) wrap.style.setProperty('--nww-' + k, v[k]); }); }
    theme(host.palette && host.palette());
    /* bar: the brand only when the host has no bar of its own; the sparks you have; the mode; the tabs */
    const bar = el('div', 'bar'); const brand = el('div', 'brand', 'Next'); brand.appendChild(el('span', null, 'World')); brand.hidden = !!host.chrome;
    const sparks = el('div', 'sparks'); sparks.title = 'Sparks: one a step, ten a project. Spend them on your avatar.';
    const mode = el('button', 'mode'); mode.type = 'button'; const tabs = el('div', 'tabs'); tabs.setAttribute('role', 'tablist');
    put(bar, brand, sparks, mode, tabs); wrap.appendChild(bar);
    const devbar = el('div', 'devbar'); devbar.hidden = true; wrap.appendChild(devbar); let devOpen = false;
    const devToggle = el('button', 'devtoggle', 'Dev tools ▾'); devToggle.type = 'button'; devToggle.hidden = true; devToggle.addEventListener('click', () => { devOpen = !devOpen; devbar.hidden = !devOpen; devToggle.textContent = devOpen ? 'Dev tools ▴' : 'Dev tools ▾'; setTimeout(fit, 0); }); wrap.insertBefore(devToggle, devbar);
    const views = {}, tabBtns = {}; const seen = new Set();
    TABS.forEach(([id, name]) => { const b = el('button', null, name); b.type = 'button'; b.setAttribute('role', 'tab'); b.dataset.view = id; b.addEventListener('click', () => show(id)); tabs.appendChild(b); tabBtns[id] = b; const v = el('section', 'view'); v.hidden = true; views[id] = v; wrap.appendChild(v); });
    let current = 'world';
    function show(id) { current = id; seen.add(id); TABS.forEach(([k]) => { tabBtns[k].setAttribute('aria-selected', String(k === id)); tabBtns[k].dataset.dot = '0'; views[k].hidden = k !== id; }); if (id === 'build') paintBuild(); if (id === 'base') paintBoard(); if (id === 'world') paintHub(); if (id === 'global') paintGlobeCard(); if (id === 'avatar') paintShop(); host.remember && host.remember('tab', id); if (typeof fit === 'function') setTimeout(fit, 0); pipFor(id); }
    const dot = id => { if (current !== id) tabBtns[id].dataset.dot = '1'; };
    function scene(w, h, label) { const sc = el('div', 'scene'); const cv = el('canvas'); cv.width = w; cv.height = h; cv.tabIndex = 0; cv.setAttribute('aria-label', label); sc.appendChild(cv); return { sc, cv }; }
    /* zoom: the wheel, and two buttons, on every scene */
    function zoomer(sc, cv, onZoom) { const z = el('div', 'zoom'); const zin = el('button', null, '+'); zin.type = 'button'; zin.setAttribute('aria-label', 'Zoom in'); const zout = el('button', null, '−'); zout.type = 'button'; zout.setAttribute('aria-label', 'Zoom out'); zin.addEventListener('click', () => onZoom(1.25)); zout.addEventListener('click', () => onZoom(0.8)); put(z, zin, zout); sc.appendChild(z); cv.addEventListener('wheel', e => { e.preventDefault(); onZoom(e.deltaY < 0 ? 1.12 : 0.9); }, { passive: false }); }
    function drag(cv, I, onTap, onDrag) { let d = null; cv.addEventListener('pointerdown', e => { d = { x: e.clientX, y: e.clientY, cx: I.cam.x, cy: I.cam.y, moved: false }; cv.setPointerCapture(e.pointerId); }); cv.addEventListener('pointermove', e => { if (!d) return; const dx = e.clientX - d.x, dy = e.clientY - d.y; if (Math.hypot(dx, dy) > 4) d.moved = true; if (d.moved) { const r = cv.getBoundingClientRect(); I.cam.x = d.cx - dx * I.W / r.width; I.cam.y = d.cy - dy * I.H / r.height; if (onDrag) onDrag(); } }); cv.addEventListener('pointerup', e => { const was = d; d = null; if (!was || was.moved) return; const r = cv.getBoundingClientRect(); const x = (e.clientX - r.left) * I.W / r.width + I.cam.x - I.W / 2, y = (e.clientY - r.top) * I.H / r.height + I.cam.y - 60; onTap([(x / (TW / 2) + y / (TH / 2)) / 2, (y / (TH / 2) - x / (TW / 2)) / 2], [x + I.W / 2 - I.cam.x, y + 60 - I.cam.y]); }); }
    /* Pip: the pineapple under every scene. One title, one line, sometimes one button */
    function pipCanvas() { const cv = el('canvas'); cv.width = 104; cv.height = 120; const I = makeIso(cv, 26, 30, 2); I.cam.y = 29; B.avatar(I, 0, 0, { body: 'pineapple', shirt: '#2f7fd6', hat: 'none' }, 0, false); return cv; }
    function guide(parent) { const box = el('div', 'pip'); const t = el('div'); const b = el('b'); const p = el('p'); put(t, b, p); const btn = el('button'); btn.type = 'button'; btn.hidden = true; put(box, pipCanvas(), t, btn); parent.appendChild(box); let onClick = null; btn.addEventListener('click', () => onClick && onClick()); return (title, line, action) => { setText(b, title); setText(p, line); if (action) { btn.hidden = false; setText(btn, action[0]); onClick = action[1]; } else { btn.hidden = true; onClick = null; } }; }
    function toast(sc) { const t = el('div', 'toast'); sc.appendChild(t); let timer = null; return text => { t.textContent = text; t.classList.add('on'); clearTimeout(timer); timer = setTimeout(() => t.classList.remove('on'), 2800); }; }
    function nav(sc, items) { const n = el('div', 'nav'); items.forEach(([t, fn]) => { const b = el('button', null, t); b.type = 'button'; b.addEventListener('click', fn); n.appendChild(b); }); sc.appendChild(n); return n; }
    function fold(parent, title, count) { const b = el('button', 'fold', title); b.type = 'button'; const c = el('small', null, count || ''); b.appendChild(c); const list = el('div', 'list'); list.hidden = true; b.setAttribute('aria-expanded', 'false'); b.addEventListener('click', () => { list.hidden = !list.hidden; b.setAttribute('aria-expanded', String(!list.hidden)); setTimeout(fit, 0); }); put(parent, b, list); return { list, count: c, open() { list.hidden = false; b.setAttribute('aria-expanded', 'true'); } }; }
    const paintSparks = () => setText(sparks, '✦ ' + state.wallet.sparks);

    /* ---- 1. NextWorld: the campus, the hub ---- */
    const w1 = scene(880, 620, 'NextWorld: NextWork Headquarters in Austin, and the learners’ plots round it. Tap your plot to enter your world. Drag to look, wheel to zoom.');
    const world = makeIso(w1.cv, 880 / (2 * 0.5), 620 / (2 * 0.5), 0.5); const wc = camTo(HQ.C[0], HQ.C[1] + 8, world.H); world.cam.x = wc.x; world.cam.y = wc.y;
    const wbadge = el('div', 'badge', 'NextWorld'); wbadge.appendChild(el('small', null, 'NextWork HQ, Austin')); w1.sc.appendChild(wbadge);
    const aimW = (gx, gy) => { const c = camTo(gx, gy, world.H); world.cam.x = c.x; world.cam.y = c.y; };
    nav(w1.sc, [['Entry', () => aimW(HQ.ARCH[0], HQ.ARCH[1] + 3)], ['HQ', () => aimW(HQ.HALL[0] + 3, HQ.HALL[1] + 2)], ['Quad', () => aimW(HQ.C[0], HQ.C[1] + 1)], ['Back road', () => aimW(HQ.HACK[0] + 6, HQ.HACK[1] + 2)], ['Ranch', () => aimW(HQ.PADDOCK[0] + 6, HQ.PADDOCK[1] + 6)], ['My plot', () => aimW(HQ.PLOTS[HQ.MINE][0], HQ.PLOTS[HQ.MINE][1])], ['All', () => { world.setScale(0.2); aimW(HQ.C[0], HQ.C[1] + 4); }]]);
    zoomer(w1.sc, w1.cv, f => world.zoom(f));
    views.world.appendChild(w1.sc); const wsay = guide(views.world);
    const hub = el('div', 'board'); views.world.appendChild(hub);
    function paintHub() {
      while (hub.firstChild) hub.removeChild(hub.firstChild); const now = Date.now(), c = S.contract(state, now), era = E.eraOf(state);
      hub.appendChild(el('h3', null, 'This week'));
      { const pin = el('div', 'pin' + (c.met ? ' met' : '')); const t = el('div'); const need = c.infra ? NW.INFRA[c.infra][0] : 'the next homes'; put(t, el('b', null, c.met ? 'Contract met: +' + c.reward + ' can live here' : 'Build ' + need), el('small', null, c.met ? 'Kept for good. A new one on Monday.' : c.week.projects + ' of ' + c.projects + ' projects or ' + c.week.steps + ' of ' + c.steps + ' steps · ' + c.daysLeft + ' days left')); const b = el('button', null, c.met ? 'Keep going' : 'Build'); b.type = 'button'; b.addEventListener('click', () => show('build')); put(pin, t, b); hub.appendChild(pin); }
      { const pin = el('div', 'pin'); const t = el('div'); put(t, el('b', null, S.landName(state) + ' · ' + era.name), el('small', null, E.score(state) + ' built · ' + S.population(state, now, lastL.capacity) + ' live there · power ' + Math.round(S.power(state, now) * 100) + '%')); const b = el('button', null, 'Go'); b.type = 'button'; b.addEventListener('click', () => show('base')); put(pin, t, b); hub.appendChild(pin); }
      hub.appendChild(el('h3', null, 'Who is building'));
      hub.appendChild(el('p', null, state.mode === 'dev' ? 'Sample builders, ranked by citizens. Real ones when NextWork publishes counts.' : 'Ranked by citizens. Real names when NextWork publishes counts.'));
      const mine = S.citizens(state, now); const rows = SAMPLE_BOARD.map(r => ({ name: r[0], where: r[1], n: r[2] })).concat([{ name: state.name === 'You' ? 'You' : state.name, where: S.landName(state), n: mine, me: true }]).sort((a, b) => b.n - a.n).slice(0, 6);
      rows.forEach((r, i) => { const pin = el('div', 'pin' + (r.me ? ' met' : '')); const t = el('div'); put(t, el('b', null, '#' + (i + 1) + ' ' + r.name), el('small', null, r.where + ' · ' + r.n + ' citizens')); pin.appendChild(t); if (r.me) { const b = el('button', null, 'Climb'); b.type = 'button'; b.addEventListener('click', () => show('build')); pin.appendChild(b); } hub.appendChild(pin); });
    }
    drag(w1.cv, world, g => { const h = HQ.hitHQ(state, g);
      if (h.kind === 'hall') { wsay('NextWork HQ', ABOUT.tagline + '.'); return; }
      if (h.kind === 'quad') { wsay('The quad', 'Benches, laptops, the middle of campus.'); return; }
      if (h.kind === 'cafe') { wsay('NextWork Cafe', 'Where people ask questions.'); return; }
      if (h.kind === 'hub') { const n = SERIES.filter(sr => sr.kind === h.hub.kind).reduce((a, sr) => a + S.doneIn(state, sr), 0); wsay(h.hub.name, 'You have built ' + n + ' from this hub.', ['Build more', () => show('build')]); return; }
      if (h.kind === 'plot' && h.owner.mine) { show('base'); return; }
      if (h.kind === 'plot' && h.owner.built) { wsay(h.owner.name, h.owner.built + ' built. Walk it when they share it.'); return; }
      if (h.kind === 'plot') { wsay('Open slot', 'A new learner starts here with a tent.'); return; }
      if (h.kind === 'staff') { wsay(h.staff.name, h.staff.says); return; }
      if (h.kind === 'paddock') { wsay('The paddock', 'Free, like the free tier.'); return; }
      if (h.kind === 'lake') { wsay('The lake', 'Ripples.'); return; }
      if (h.kind === 'arch') { wsay('The entry', 'Everyone comes in this way.'); return; }
      if (h.kind === 'lot') { wsay('Parking', 'Park, walk in under the arch.'); return; }
      if (h.kind === 'rack') { wsay('Bike racks', 'Ride in, rack it, walk in.'); return; }
      if (h.kind === 'soon') { wsay(h.name, 'Coming soon. The cranes are turning.'); return; }
      if (h.kind === 'hack') { wsay('NextWork Hackathon', 'A weekend, a brief, a build, a demo.'); return; }
      if (h.kind === 'games') { wsay('NextWork Games', 'Challenges, leaderboards, bragging rights.'); return; }
      if (h.kind === 'lodge') { wsay('NextWork Lodge', 'Where learners stay a while.'); return; }
      if (h.kind === 'pasture') { wsay('The pasture', 'Cows. It is a ranch.'); return; }
      if (h.kind === 'coops') { wsay('The coops', 'Chickens. Also a ranch.'); return; }
      wsay('Campus', 'Tap a hub, a person, or your plot.'); });

    /* ---- 2. My World ---- */
    const me = Land.makeMe(state); let anim = null; const fx = []; let lastL = S.layout(state); let placing = null;
    const b1 = scene(880, 620, 'Your land. Tap where you want to go and you take the roads there; arrow keys walk too. Tap a building for its project. Drag to look, wheel to zoom.');
    const base = makeIso(b1.cv, 440, 310); Object.assign(base.cam, camTo(me.gx, me.gy, 310));
    const hud = el('button', 'hud'); hud.type = 'button'; hud.title = 'Where you are and what to do next'; const shield = el('div', 'shield', '1'); const who = el('div', 'who'); const whoB = el('b', null, S.landName(state)); const whoS = el('small', null, ''); const whoN = el('small', 'next', ''); put(who, whoB, whoS, whoN); put(hud, shield, who); b1.sc.appendChild(hud);
    nav(b1.sc, [['Home', () => { Land.goTo(me, lastL.paths, [S.HOME[0] + 1.5, S.HOME[1] + 2.5]); me.follow = true; }], ['HQ', () => show('world')], ['Build', () => show('build')]]);
    zoomer(b1.sc, b1.cv, f => base.zoom(f));
    const btoast = toast(b1.sc); views.base.appendChild(b1.sc);
    const pick = el('div', 'dash'); pick.hidden = !!state.biome; const pickT = el('h3', null, 'Choose your land'); const pickP = el('div', 'cap', 'Pick once. It is yours for good. Every land grows the same way.'); const pickList = el('div', 'list'); put(pick, pickT, pickP, pickList); b1.sc.appendChild(pick);
    Land.TERRAIN_KEYS.forEach(k => { const row = el('div', 'row going'); const nn = el('div', 'n'); put(nn, el('b', null, Land.TERRAINS[k].name), el('small', null, Land.TERRAINS[k].blurb)); const b = el('button', null, 'This one'); b.type = 'button'; b.addEventListener('click', () => { state.biome = k; save(); S.forget(); lastL = S.layout(state); pick.hidden = true; bsay('Nice', 'Now pick a project from the board.', ['Show me', () => board.scrollIntoView({ behavior: 'smooth', block: 'start' })]); }); put(row, el('i', null, TERRAIN_ICON[k]), nn, el('div', 'v', ''), b); pickList.appendChild(row); });
    const levelup = el('div', 'levelup'); levelup.hidden = true; const luT = el('b'); const luS = el('small'); const luP = el('p'); put(levelup, luS, luT, luP); b1.sc.appendChild(levelup); let luTimer = null, lastEra = E.eraOf(state).name;
    function showLevelUp(era) { luS.textContent = era.n + ' projects'; luT.textContent = era.name + ' unlocked'; luP.textContent = E.LEVEL_UP[era.plan.id] || ''; levelup.hidden = false; clearTimeout(luTimer); luTimer = setTimeout(() => { levelup.hidden = true; }, 6000); bsay(era.name + ' unlocked', 'What you know protects what you build.'); }
    /* the dashboard panel: tap the shield */
    const dash = el('div', 'dash'); dash.hidden = true; const dashT = el('h3'); const dashList = el('div', 'list'); const dashClose = el('button', 'btn', 'Close'); dashClose.type = 'button'; dashClose.addEventListener('click', () => { dash.hidden = true; }); put(dash, dashT, dashList, dashClose); b1.sc.appendChild(dash);
    function paintDash() { const era = E.eraOf(state), ne = E.nextEra(state), nx = S.nextProject(state), now = Date.now(), L = lastL, pw = S.power(state, now), c = S.contract(state, now); dashT.textContent = S.landName(state) + ' · ' + era.name; while (dashList.firstChild) dashList.removeChild(dashList.firstChild);
      let n = 0; const step = (t, sub, fn) => { const row = el('div', 'row' + (fn ? ' going' : '')); const nn = el('div', 'n'); put(nn, el('b', null, t), el('small', null, sub)); put(row, el('i', null, String(++n)), nn, el('div', 'v', '')); if (fn) { const b = el('button', null, 'Go'); b.type = 'button'; b.addEventListener('click', fn); row.appendChild(b); } dashList.appendChild(row); };
      if (nx) step('Next: ' + nx.title, 'Tick its steps. Walls rise here.', () => { dash.hidden = true; show('build'); });
      step('Power ' + Math.round(pw * 100) + '%', pw >= 0.75 ? 'Lights on. One project a day keeps it.' : pw >= 0.5 ? 'Half the lights. A step adds 5%.' : pw >= 0.25 ? 'Mill stopped, fields fallow. Build today.' : 'Embers. One project brings it all back.');
      step(S.population(state, now, L.capacity) + ' of ' + L.capacity + ' live here', 'One moves in per step while powered.');
      step(c.met ? 'Contract met this week' : 'Contract: ' + (c.infra ? NW.INFRA[c.infra][0] : 'homes'), c.met ? '+' + c.reward + ' room, for good.' : c.week.projects + '/' + c.projects + ' projects or ' + c.week.steps + '/' + c.steps + ' steps.');
      step(ne ? (ne.n - E.score(state)) + ' more to ' + ne.name : 'A kingdom', ne ? 'It brings ' + (NW.INFRA[ne.plan.builds[0] && ne.plan.builds[0].kind] || ['new streets'])[0].toLowerCase() + ' and more.' : 'Every era, earned.'); }
    hud.addEventListener('click', () => { if (placing) { placing = null; bsay('Kept the pegged lot', 'It goes where the pegs are.'); return; } paintDash(); dash.hidden = !dash.hidden; });
    const card = el('div', 'card'); card.hidden = true; const cIc = el('div', 'ic'); const cT = el('div'); const cB = el('b'); const cS = el('small'); put(cT, cB, cS); const acts = el('div', 'acts'); const cOpen = el('button', null, 'Open project'); cOpen.type = 'button'; const cNext = el('button', 'up', 'Next part'); cNext.type = 'button'; put(acts, cOpen, cNext); put(card, cIc, cT, acts); views.base.appendChild(card);
    const bsay = guide(views.base); const board = el('div', 'board'); views.base.appendChild(board);
    function startPlacing(title) { placing = title; show('base'); bsay('Where do you want it?', 'Tap an outlined lot. Tap the shield to keep the pegged one.'); btoast('Pick a lot'); }
    function paintBoard() {
      while (board.firstChild) board.removeChild(board.firstChild);
      const empty = state.done.length === 0; board.appendChild(el('h3', null, empty ? 'Start here' : 'Next on the board'));
      board.appendChild(el('p', null, empty ? 'Pick one. Open it. Tick its steps.' : 'Where you left off, and two worth a look.'));
      const picks = []; const nx = S.nextProject(state); if (nx && !empty) picks.push([nx.title, nx.series.id, 'Part ' + (S.doneIn(state, nx.series) + 1) + ' of ' + nx.series.projects.length + ' · ' + nx.series.name]);
      START_HERE.forEach(p => { if (picks.length < 3 && !state.done.includes(p[0]) && !picks.some(x => x[0] === p[0])) picks.push(p); });
      picks.forEach(p => { const sr = SERIES.find(x => x.id === p[1]); const pin = el('div', 'pin'); const t = el('div'); put(t, el('b', null, p[0]), el('small', null, p[2])); const b = el('button', null, 'Open'); b.type = 'button'; b.addEventListener('click', () => { state.building = p[0]; save(); host.openProject(p[0], sr); bsay('Go', 'Tick steps there. Walls rise here.'); }); put(pin, t, b); board.appendChild(pin); });
      if (!picks.length) board.appendChild(el('p', null, 'Every project is built. The land is yours.'));
    }
    function showCard(b) { card.hidden = false; cIc.textContent = ICON[b.kind]; cB.textContent = b.series ? b.title : b.list.name; cS.textContent = (b.series ? b.series.name + ' · part ' + b.part + ' of ' + b.of : 'Learn list · ' + b.part + ' of ' + b.of) + ' · room for ' + clamp(Math.ceil((b.xp || 60) / 30), 2, 5); const nxt = b.series ? b.series.projects.find(pr => !state.done.includes(pr[0])) : null; cNext.disabled = !nxt; cNext.textContent = nxt ? 'Next: ' + nxt[0] : b.series ? 'Series complete' : 'Yours'; cNext.onclick = () => { if (nxt) { state.building = nxt[0]; save(); host.openProject(nxt[0], b.series); } }; cOpen.onclick = () => host.openProject(b.series ? b.title : b.list.name, b.series); Land.goTo(me, lastL.paths, [b.gx + 0.5, b.gy + 1.4]); me.follow = true; }
    drag(b1.cv, base, g => { const L = lastL;
      if (placing) { const q = S.nearestLot(state, g); if (!q) { bsay('Not there', 'Pick an outlined lot on a lane.'); return; } state.sites[placing] = q; state.building = placing; if (state.mode === 'dev' && !state.steps[placing]) state.steps[placing] = { done: 0, total: 7 }; const t = placing; placing = null; save(); lastL = S.layout(state); btoast('Pegged out'); bsay('Pegged out', t + ' goes here.'); paintBoard(); paintBuild(); show('build'); return; }
      { const ex = L.plan.roads[0].from; if (Math.abs(g[0] - ex[0] + 0.5) < 1.6 && Math.abs(g[1] - ex[1] + 0.5) < 1.6) { show('world'); aimW(HQ.PLOTS[HQ.MINE][0], HQ.PLOTS[HQ.MINE][1]); return; } }
      const hit = Land.hit(L, g); if (hit) { showCard(hit); return; } card.hidden = true;
      if (Math.abs(g[0] - S.HOME[0] - 1) < 1.8 && Math.abs(g[1] - S.HOME[1] - 1) < 1.8) { const ne = E.nextEra(state); bsay(S.landName(state), ne ? (ne.n - E.score(state)) + ' more projects to ' + ne.name + '.' : 'A kingdom.'); Land.goTo(me, L.paths, [S.HOME[0] + 1.5, S.HOME[1] + 2.5]); me.follow = true; return; }
      if (g[0] >= 0 && g[1] >= 0 && g[0] < S.LAND && g[1] < S.LAND) { if (Land.goTo(me, L.paths, g)) me.follow = true; else bsay('No road there', 'Roads reach everything built.'); } }, () => { me.follow = false; });
    b1.cv.addEventListener('keydown', e => { if (['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'w', 'a', 's', 'd'].includes(e.key)) { me.keys[e.key] = true; e.preventDefault(); } });
    b1.cv.addEventListener('keyup', e => { delete me.keys[e.key]; }); b1.cv.addEventListener('blur', () => { me.keys = {}; });
    function finish(title, sr) { S.finish(state, title); save(); lastL = S.layout(state); const b = lastL.buildings.find(x => x.title === title); anim = { title, start: performance.now() }; btoast('Built: ' + title); bsay('Built!', 'People can move in now. +10 sparks.', ['See it', () => show('base')]); if (b) { fx.push({ type: 'sparkle', gx: b.gx + 0.5, gy: b.gy + 0.5, seed: Math.random() * 6, start: performance.now() + 1500, life: 900 }); Land.goTo(me, lastL.paths, [b.gx + 0.5, b.gy + 1.6]); me.follow = true; } dot('base'); dot('world'); paintSparks(); paintBoard(); paintBuild(); paintDev(); }

    /* ---- 3. Avatar: you, and the shop ---- */
    const av = state.avatar; const a1 = scene(880, 400, 'Your avatar, walking your land'); const avI = makeIso(a1.cv, 440, 200); const avc = camTo(2, 2, 200); avI.cam.x = avc.x; avI.cam.y = avc.y + 10;
    const avWrap = el('div', 'av'); avWrap.appendChild(a1.sc); const asay = guide(avWrap); const opts = el('div', 'opts'); avWrap.appendChild(opts); views.avatar.appendChild(avWrap);
    const field = (label, id, value, onChange) => { const row = el('div', 'grp'); const inp = el('input'); inp.id = id; inp.type = 'text'; inp.maxLength = 28; inp.value = value; inp.setAttribute('aria-label', label); inp.addEventListener('change', () => onChange(inp.value.trim())); put(row, el('span', null, label), inp); opts.appendChild(row); };
    field('Name', 'nww-name', state.name, v => { state.name = v || 'You'; save(); whoB.textContent = S.landName(state); });
    field('Your land', 'nww-land', state.land, v => { state.land = v; save(); whoB.textContent = S.landName(state); });
    const shopGroups = [];
    function choices(label, k, list, swatch) { const g = el('div', 'grp'); g.appendChild(el('span', null, label)); const paint = () => g.querySelectorAll('button').forEach(b => { const item = k + ':' + b.dataset.v, locked = !S.owns(state, item); b.setAttribute('aria-pressed', String(b.dataset.v === av[k])); b.dataset.locked = locked ? '1' : '0'; if (!swatch) b.textContent = b.dataset.t + (locked ? ' · ' + S.PRICES[item] + '✦' : ''); }); list.forEach(([v, t]) => { const b = el('button', swatch ? 'sw' : null, swatch ? '' : t); b.type = 'button'; b.dataset.v = v; b.dataset.t = t; if (swatch) { b.style.background = v; b.title = t; b.setAttribute('aria-label', t); } b.addEventListener('click', () => { const item = k + ':' + v; if (!S.owns(state, item)) { if (!S.buy(state, item)) { asay('Not yet', 'That is ' + S.PRICES[item] + ' sparks. You have ' + state.wallet.sparks + '. A step is a spark.', ['Earn some', () => show('build')]); return; } asay('Yours', t + ' unlocked for ' + S.PRICES[item] + ' sparks.'); } av[k] = v; save(); paintSparks(); paint(); }); g.appendChild(b); }); paint(); opts.appendChild(g); shopGroups.push(paint); }
    choices('Body', 'body', [['pineapple', 'Pineapple'], ['person', 'Person'], ['robot', 'Robot'], ['cat', 'Cat']]);
    choices('Shirt', 'shirt', [['#2f7fd6', 'Blue'], ['#e8552f', 'Red'], ['#3fa66b', 'Green'], ['#f2b42a', 'Gold'], ['#8f5fd1', 'Purple'], ['#1c1f26', 'Black'], ['#f4f1e8', 'White']], true);
    choices('Hat', 'hat', [['none', 'None'], ['cap', 'Cap'], ['cowboy', 'Cowboy'], ['hard', 'Hard hat'], ['beanie', 'Beanie']]);
    choices('Hat colour', 'hatColour', [['#8a5a3a', 'Tan'], ['#1c1f26', 'Black'], ['#ffc531', 'Yellow'], ['#e8552f', 'Red'], ['#2f7fd6', 'Blue']], true);
    choices('Skin', 'skin', [['#ffd6ad', 'Light'], ['#e8b48a', 'Medium'], ['#b87a4b', 'Tan'], ['#7a4b2a', 'Deep'], ['#4a2e1a', 'Dark']], true);
    choices('Hair', 'hair', [['#4a2e1a', 'Brown'], ['#1c1f26', 'Black'], ['#d9b24c', 'Blond'], ['#b03a2e', 'Red'], ['#9aa3b0', 'Grey']], true);
    function paintShop() { shopGroups.forEach(f => f()); asay('Your avatar', 'Walks your land. Dashed ones cost sparks: a step is a spark, a project is ten.'); }

    /* ---- 4. My Build ---- */
    const bt = el('div', 'tiles'); const tWhere = el('div', 'tile wide'); const tWb = el('b'); const tWs = el('span'); const tWbar = el('div', 'barx'); const tWi = el('i'); tWbar.appendChild(tWi); put(tWhere, el('small', null, 'Your land'), tWb, tWs, tWbar);
    const tNeed = el('div', 'tile'); const tNb = el('b'); const tNs = el('span'); put(tNeed, el('small', null, 'This week'), tNb, tNs);
    const tPow = el('div', 'tile'); const tPb = el('b'); const tPs = el('span'); const tPbar = el('div', 'barx gold'); const tPi = el('i'); tPbar.appendChild(tPi); put(tPow, el('small', null, 'Power'), tPb, tPs, tPbar); put(bt, tWhere, tNeed, tPow); views.build.appendChild(bt);
    const pName = el('h3'); const pSub = el('div', 'cap'); put(views.build, pName, pSub);
    const openBtn = el('button', 'btn go', 'Open the project'); openBtn.type = 'button'; views.build.appendChild(openBtn);
    const prog = el('div', 'prog'); const progBar = el('div', 'barx'); const progI = el('i'); progBar.appendChild(progI); const progT = el('small'); put(prog, progBar, progT); views.build.appendChild(prog);
    const psay = guide(views.build);
    const steps = el('div', 'steps'); views.build.appendChild(steps);
    const stepBtn = el('button', 'btn', 'Complete the next step'); stepBtn.type = 'button'; views.build.appendChild(stepBtn);
    const s1 = scene(880, 500, 'The building site. Tap the nails as they pop up to hammer them in.'); const site = makeIso(s1.cv, 440, 250); const sbadge = el('div', 'badge', ''); s1.sc.appendChild(sbadge); zoomer(s1.sc, s1.cv, f => site.zoom(f)); views.build.appendChild(s1.sc);
    const game = { nails: [], hit: 0, last: 0 };
    drag(s1.cv, site, (g, lg) => { const n = game.nails.find(x => !x.done && Math.hypot(x.sx - lg[0], x.sy - lg[1]) < 44); if (n) { n.done = true; n.at = performance.now(); game.hit++; const cs = current_site ? (state.craft[current_site.title] = (state.craft[current_site.title] || 0) + 1) : 0; if (state.mode === 'dev' && current_site && cs % 5 === 0) tickStep(); paintBuild(); } });
    const placeBtn = el('button', 'link', 'Placed by the plan. Want it elsewhere? Pick a lot'); placeBtn.type = 'button'; views.build.appendChild(placeBtn);
    const needFold = fold(views.build, 'What this era needs'); const pathFold = fold(views.build, 'The path'); const catFold = fold(views.build, 'The catalogue'); const libFold = fold(views.build, 'Your library');
    let current_site = null; const bs = { lastAt: -9000 };
    function stepsOf(title) { const st = state.steps[title]; return st ? { done: st.done, total: st.total } : { done: 0, total: 7 }; }
    function tickStep() { if (!current_site) return; const st = stepsOf(current_site.title); if (st.done >= st.total) return; applyProject({ title: current_site.title, done: st.done + 1, total: st.total, at: Date.now() }); }
    function paintBuild() {
      const era = E.eraOf(state), ne = E.nextEra(state), sc = E.score(state), now = Date.now(), pw = S.power(state, now), c = S.contract(state, now);
      setText(tWb, era.name + ' · ' + sc + ' built'); setText(tWs, ne ? (ne.n - sc) + ' more to ' + ne.name : 'The whole thing'); tWi.style.width = (ne ? (sc - era.n) / (ne.n - era.n) * 100 : 100) + '%';
      setText(tNb, c.met ? 'Met ✓' : (c.infra ? NW.INFRA[c.infra][0] : 'Homes')); setText(tNs, c.met ? '+' + c.reward + ' room, kept' : c.week.projects + '/' + c.projects + ' projects or ' + c.week.steps + '/' + c.steps + ' steps');
      setText(tPb, Math.round(pw * 100) + '%'); setText(tPs, pw >= 0.75 ? 'Lights on' : pw >= 0.5 ? 'Half the lights' : pw >= 0.25 ? 'Mill stopped' : 'Embers'); tPi.style.width = Math.round(pw * 100) + '%';
      const nx = S.nextProject(state); current_site = nx ? Land.siteFor(state) : null; const placed = !!current_site; const st = current_site ? stepsOf(current_site.title) : { done: 0, total: 0 };
      const inf = current_site && current_site.infra ? NW.INFRA[current_site.infra.kind] : null;
      setText(pName, nx ? nx.title : 'Every project is built'); setText(pSub, nx ? (inf ? 'Builds the ' + inf[0].toLowerCase() + ': ' + inf[1] : 'A home on the next lot, room for ' + clamp(Math.ceil(nx.xp / 30), 2, 5)) + ' · ' + nx.series.name : '');
      progI.style.width = (st.total ? st.done / st.total * 100 : 0) + '%'; setText(progT, st.total ? st.done + ' of ' + st.total + ' steps · ' + (state.craft[nx && nx.title] || 0) + ' nails' : 'Open it and tick the first step');
      if (nx) psay(st.done >= st.total && st.total ? 'Done' : st.done ? 'Step ' + st.done + ' of ' + st.total : 'Start', NW.LESSONS[(st.done + (NW.PROJECTS.findIndex(p => p.title === nx.title) | 0)) % NW.LESSONS.length]); else psay('Everything is built', 'Your library is next.');
      placeBtn.hidden = !nx || !!inf; placeBtn.onclick = () => nx && startPlacing(nx.title);
      s1.sc.hidden = !placed; if (current_site) { const cc = camTo(current_site.gx + 0.5, current_site.gy + 0.5, site.H); site.cam.x = cc.x; site.cam.y = cc.y + 20; }
      while (steps.firstChild) steps.removeChild(steps.firstChild);
      const names = state.mode === 'dev' && !state.steps[nx && nx.title] ? ['Set up', 'Build it', 'Connect it', 'Test it', 'Secure it', 'Document it', 'Clean up'] : null;
      for (let i = 0; i < st.total; i++) { const d = el('div', 'step' + (i < st.done ? ' done' : i === st.done ? ' now' : '')); put(d, el('i', null, i < st.done ? '✓' : String(i + 1)), el('b', null, names ? names[i] || 'Step ' + (i + 1) : 'Step ' + (i + 1))); steps.appendChild(d); }
      stepBtn.hidden = state.mode !== 'dev' || !placed; stepBtn.disabled = !current_site || st.done >= st.total; setText(stepBtn, st.done >= st.total && st.total ? 'All steps done' : 'Complete step ' + (st.done + 1) + ' of ' + st.total);
      openBtn.hidden = !placed; openBtn.disabled = !current_site; openBtn.onclick = () => current_site && host.openProject(current_site.title, current_site.series);
      { const L = S.layout(state), plan = L.plan, list = needFold.list; while (list.firstChild) list.removeChild(list.firstChild); setText(needFold.count, L.infra.length + ' of ' + plan.builds.length); plan.builds.forEach((b, i) => { const info = NW.INFRA[b.kind] || [b.kind, '']; const built = i < L.infra.length, isNext = !built && i === L.infra.length; const row = el('div', 'row' + (built ? ' full' : isNext ? ' going' : '')); const nn = el('div', 'n'); put(nn, el('b', null, info[0]), el('small', null, info[1])); put(row, el('i', null, built ? '✓' : isNext ? '▶' : String(i + 1)), nn, el('div', 'v', built ? 'built' : isNext ? 'next' : '')); list.appendChild(row); }); const homesRow = el('div', 'row' + (L.infra.length >= plan.builds.length ? ' going' : '')); const hn = el('div', 'n'); put(hn, el('b', null, 'Homes'), el('small', null, 'Every project after: a home, room by what it took.')); put(homesRow, el('i', null, '🏠'), hn, el('div', 'v', L.buildings.filter(b => b.series).length + ' built')); list.appendChild(homesRow); }
      { const list = pathFold.list; while (list.firstChild) list.removeChild(list.firstChild); const nxTitle = nx ? nx.title : ''; let shown = 0; const donePos = NW.PROJECTS.findIndex(pr => pr.title === nxTitle); setText(pathFold.count, state.done.length + ' of 90');
        NW.PROJECTS.forEach((pr, i) => { const d = state.done.includes(pr.title); const near = Math.abs(i - Math.max(donePos, 0)) <= 4; if (!d && !near && shown > 12) return; if (d && i < donePos - 3) return; shown++; const sr = SERIES.find(x => x.id === pr.series); const row = el('div', 'row quiet' + (d ? ' full' : pr.title === nxTitle ? ' going' : '')); const nn = el('div', 'n'); put(nn, el('b', null, (i + 1) + '. ' + pr.title), el('small', null, sr.name + ' · ' + KIND_NAME[sr.kind].toLowerCase())); put(row, el('i', null, d ? '✓' : ICON[sr.kind]), nn, el('div', 'v', d ? 'built' : pr.title === nxTitle ? 'next' : '')); if (!d && pr.title !== nxTitle) { const b = el('button', null, 'Jump to this one'); b.type = 'button'; b.addEventListener('click', () => { state.building = pr.title; save(); paintBuild(); paintBoard(); }); row.appendChild(b); } list.appendChild(row); }); }
      { const list = catFold.list; while (list.firstChild) list.removeChild(list.firstChild); setText(catFold.count, SERIES.filter(sr => S.doneIn(state, sr) === sr.projects.length).length + ' of ' + SERIES.length + ' complete');
        SERIES.forEach(sr => { const d = S.doneIn(state, sr), n = sr.projects.length; const row = el('div', 'row quiet' + (d === n ? ' full' : d ? ' going' : '')); const nn = el('div', 'n'); const barx = el('div', 'barx'); const bi = el('i'); bi.style.width = (d / n * 100) + '%'; barx.appendChild(bi); put(nn, el('b', null, sr.name), el('small', null, KIND_NAME[sr.kind] + (d ? ' · tier ' + S.tierIn(state, sr) : '')), barx); const v = el('div', 'v', d + ' / ' + n); put(row, el('i', null, ICON[sr.kind]), nn, v); const nxt = sr.projects.find(pr => !state.done.includes(pr[0])); if (nxt) { const b = el('button', null, (d ? 'Next: ' : 'Start: ') + nxt[0]); b.type = 'button'; b.addEventListener('click', () => { state.building = nxt[0]; save(); paintBuild(); paintBoard(); }); row.appendChild(b); } list.appendChild(row); }); }
      { const list = libFold.list; while (list.firstChild) list.removeChild(list.firstChild); const lt = state.lists.reduce((a, l) => a + l.total, 0), ld = state.lists.reduce((a, l) => a + l.done, 0); setText(libFold.count, state.lists.length ? ld + ' of ' + lt + ' built' : 'none yet');
        if (!state.lists.length) list.appendChild(el('div', 'cap', state.mode === 'dev' ? 'No learn lists in this seed.' : 'Open your portfolio on nextwork.ai. Your lists appear here, pegged out; the crew builds one a day while the power holds.'));
        state.lists.forEach(l => { const row = el('div', 'row' + (l.done >= l.total ? ' full' : l.done ? ' going' : '')); const nn = el('div', 'n'); put(nn, el('b', null, l.name), el('small', null, l.blurb || KIND_NAME[l.kind] + ' row')); const v = el('div', 'v', l.done + ' / ' + l.total); put(row, el('i', null, '🌉'), nn, v); list.appendChild(row); }); }
    }
    stepBtn.addEventListener('click', tickStep);
    /* a reading of the project page (or the dev button, or the page pineapple): steps rise, sparks drop, walls go up */
    function applyProject(r) { const was = S.score(state); S.applyProjectReading(state, r, r.at || Date.now()); save(); lastL = S.layout(state); const p = state.pulse; if (p && p.steps) bs.lastAt = performance.now();
      if (p && p.finished) { const b = lastL.buildings.find(x => x.title === p.title); anim = { title: p.title, start: performance.now() }; btoast('Built: ' + p.title); if (b) { fx.push({ type: 'sparkle', gx: b.gx + 0.5, gy: b.gy + 0.5, seed: Math.random() * 6, start: performance.now() + 1500, life: 900 }); Land.goTo(me, lastL.paths, [b.gx + 0.5, b.gy + 1.6]); me.follow = true; } bsay('Built!', 'People can move in now. +10 sparks.', ['See it', () => show('base')]); psay('Built!', 'It stands. Next project, next building.', ['Next', () => paintBuild()]); dot('base'); dot('world'); }
      else if (p && p.steps) { psay('Step ' + p.done + ' of ' + p.total, '+' + p.steps + ' spark' + (p.steps === 1 ? '' : 's') + ', +' + (5 * p.steps) + '% power. ' + NW.LESSONS[p.done % NW.LESSONS.length]); if (current !== 'build') dot('build'); }
      if (S.score(state) !== was) paintDev(); paintSparks(); paintBuild(); paintBoard(); }

    /* ---- 5. Globe: the world, and your place in it ---- */
    const g1 = scene(880, 620, 'The globe, with NextWork in Austin and learners as plots of land. Drag to spin it, wheel to zoom.'); const gctx = g1.cv.getContext('2d');
    const gview = { yaw: -97, pitch: 25, spin: true, zoom: 1 }; let ghits = [];
    const gbadge = el('div', 'badge', 'Globe'); const gsmall = el('small'); gbadge.appendChild(gsmall); g1.sc.appendChild(gbadge); views.global.appendChild(g1.sc);
    nav(g1.sc, [['Austin', () => { gview.yaw = -97; gview.pitch = 30; gview.spin = false; }], ['Europe', () => { gview.yaw = 15; gview.pitch = 50; gview.spin = false; }], ['Africa', () => { gview.yaw = 20; gview.pitch = 5; gview.spin = false; }], ['Asia', () => { gview.yaw = 90; gview.pitch = 30; gview.spin = false; }], ['Spin', () => { gview.spin = !gview.spin; }], ['My land', () => show('base')]]);
    zoomer(g1.sc, g1.cv, f => { gview.zoom = clamp(gview.zoom * f, 0.6, 3); });
    const gsay = guide(views.global);
    function paintGlobeCard() { const mine = S.citizens(state, Date.now()); const rank = 1 + SAMPLE_BOARD.filter(r => r[2] > mine).length; gsay('You: #' + rank + ' of ' + (SAMPLE_BOARD.length + 1) + ' · ' + mine + ' citizens', state.mode === 'dev' ? 'Sample rank. Real when NextWork publishes counts.' : 'Rank against sample builders until NextWork publishes counts.', ['Climb', () => show('build')]); }
    let gdrag = null;
    g1.cv.addEventListener('pointerdown', e => { gdrag = { x: e.clientX, y: e.clientY, yaw: gview.yaw, pitch: gview.pitch, moved: false }; g1.cv.setPointerCapture(e.pointerId); });
    g1.cv.addEventListener('pointermove', e => { if (!gdrag) return; const dx = e.clientX - gdrag.x, dy = e.clientY - gdrag.y; if (Math.hypot(dx, dy) > 4) { gdrag.moved = true; gview.spin = false; } if (gdrag.moved) { const r = g1.cv.getBoundingClientRect(); gview.yaw = gdrag.yaw + dx / r.width * 240 / gview.zoom; gview.pitch = clamp(gdrag.pitch + dy / r.height * 160 / gview.zoom, -80, 80); } });
    g1.cv.addEventListener('pointerup', e => { const was = gdrag; gdrag = null; if (!was || was.moved) return; const r = g1.cv.getBoundingClientRect(); const x = (e.clientX - r.left) * g1.cv.width / r.width, y = (e.clientY - r.top) * g1.cv.height / r.height; const hit = ghits.find(h => Math.hypot(h.x - x, h.y - y) < h.r + 4); if (!hit) { gsay('Open water', 'Drag to spin the globe.'); return; } if (hit.hq) { gsay('NextWork · Austin', 'Home of the campus.', ['Visit HQ', () => show('world')]); return; } gsay(hit.d[0], hit.d[3] + ' learners building. Sample numbers.'); });

    /* ---- fit: every scene takes the room the pane gives it, so a full-browser pane shows the whole tab ---- */
    const SCENES = [[world, w1, 0.62], [base, b1, 0.62], [avI, a1, 0.34], [site, s1, 0.44], [null, g1, 0.62]];
    const hostEl = root.host || root;   /* the pane or the demo's panel: the room there is, not the content's own height */
    function fit() { const cw = Math.max(240, wrap.clientWidth - 24), ch = hostEl.clientHeight || 0; const chrome = bar.offsetHeight + (devbar.hidden ? 0 : devbar.offsetHeight); const avail = Math.max(300, ch - chrome - 40);
      SCENES.forEach(([I, sc, share]) => {
        /* the scene takes the height the rest of its tab leaves it, with a floor of the old share; a wide pane gets a tall map, not a letterbox */
        const view = sc.sc.parentElement; let extras = 0; if (view && !view.hidden) Array.prototype.forEach.call(view.children, c => { if (c !== sc.sc && !c.hidden && !c.classList.contains('board') && !c.classList.contains('list') && !c.classList.contains('fold') && c.tagName !== 'H3') extras += c.offsetHeight + 12; });
        const h = Math.round(Math.max(220, Math.min(Math.max(avail - extras - 20, avail * share), cw * 1.1))); if (I) I.resize(cw * 2, h * 2); else if (sc.cv.width !== cw * 2 || sc.cv.height !== h * 2) { sc.cv.width = cw * 2; sc.cv.height = h * 2; } }); }
    if (window.ResizeObserver) { const ro = new ResizeObserver(fit); ro.observe(wrap); if (hostEl !== wrap && hostEl.nodeType === 1) ro.observe(hostEl); } fit();

    /* ---- Pip speaks for the tab you are on, and when something happens ---- */
    function pipFor(id) { const nx = S.nextProject(state), pw = S.power(state, Date.now());
      if (id === 'world') wsay('Hi, I am Pip', state.done.length ? 'This is HQ. Your plot is outside the fence.' : 'Welcome to NextWork HQ. Tap your plot to start.', ['My plot', () => show('base')]);
      if (id === 'base') { if (!state.biome) bsay('Pick your land', 'It is yours for good.'); else if (!state.done.length) bsay('Pick a project', 'One from the board below. Then tick its steps.'); else if (pw < 0.5) bsay('Power is low', 'One project today brings the lights back.', ['Build', () => show('build')]); else if (nx) bsay('Next', nx.title, ['Build it', () => show('build')]); else bsay('Everything is built', 'Walk it. It is yours.'); }
      if (id === 'build' && nx) { const st = stepsOf(nx.title); if (!st.done) psay('Start', 'Open it. Tick a step there, a wall rises here.'); }
      if (id === 'global') paintGlobeCard(); if (id === 'avatar') paintShop(); }

    /* ---- mode, dev controls ---- */
    function paintMode() { setTimeout(fit, 0); mode.textContent = state.mode === 'dev' ? 'Dev' : 'Live'; mode.title = state.mode === 'dev' ? 'Dev: simulate and reset. Tap for live data.' : 'Live: real data only. Tap for dev tools.'; mode.dataset.on = state.mode; devToggle.hidden = state.mode !== 'dev'; devbar.hidden = state.mode !== 'dev' || !devOpen; }
    mode.addEventListener('click', () => { state.mode = state.mode === 'dev' ? 'prod' : 'dev'; if (state.mode === 'prod' && host.production) { const p = S.normalise(host.production()); state.done = p.done; state.lists = p.lists; state.steps = p.steps; delete state.power; delete state.hour; delete state.dayMs; } save(); lastL = S.layout(state); paintMode(); paintDev(); paintBuild(); paintBoard(); paintSparks(); });
    const perf = { t: 0, ema: 16 }; let fpsSpan = null, ioBox = null;
    function devRow(label, items) { const row = el('div', 'devrow'); row.appendChild(el('span', null, label)); items.forEach(it => { if (!it) return; if (it.nodeType) { row.appendChild(it); return; } const [t, fn, pressed] = it; const b = el('button', null, t); b.type = 'button'; if (pressed != null) b.setAttribute('aria-pressed', String(pressed)); b.addEventListener('click', () => { fn(); save(); lastL = S.layout(state); paintDev(); paintBuild(); paintBoard(); paintSparks(); }); row.appendChild(b); }); devbar.appendChild(row); return row; }
    function refresh(msg) { whoB.textContent = S.landName(state); if (msg) bsay(msg[0], msg[1]); }
    function paintDev() { while (devbar.firstChild) devbar.removeChild(devbar.firstChild); const e = E.eraOf(state), ne = E.nextEra(state), nx = S.nextProject(state), nl = nx ? null : S.nextListProject(state);
      devRow(e.name + ' · ' + E.score(state) + (ne ? ' · next at ' + ne.n : ''), []);
      devRow('Seed', [['Fresh', () => { const m = state.mode, a = state.avatar, nm = state.name, ld = state.land; Object.assign(state, S.fresh()); state.mode = m; state.avatar = a; state.name = nm; state.land = ld; refresh(['Reset', 'A tent, a board, one oak.']); }]].concat([5, 15, 35, 60, 90, 120].map(n => [String(n), () => { const m = state.mode; S.seed(state, Math.min(90, n), state.name); if (n > 90) state.lists.forEach(l => { l.done = l.total; }); state.mode = m; state.land = state.land || 'Pineapple Kingdom'; state.life.at = Date.now(); state.life.power = 1; state.life.citizens = Math.max(state.life.citizens, Math.floor(n / 3)); refresh([n + ' built', 'Seeded. The lists are pegged out for the crew.']); }])).concat([['Finish all', () => { state.done = NW.PROJECTS.map(p => p.title); state.lists.forEach(l => { l.done = l.total; }); state.building = ''; refresh(['All of it', 'The whole valley.']); }]]));
      devRow('Build', [[nx ? 'Build next: ' + nx.title.slice(0, 26) : nl ? 'Build next: ' + nl.name.slice(0, 20) + ' ' + (nl.done + 1) : 'All built', () => { if (nx) finish(nx.title, nx.series); else if (nl) { nl.done++; btoast('Built: ' + nl.name + ' ' + nl.done + ' of ' + nl.total); } }], ['+1 step', () => tickStep()], ['Undo', () => { const ll = state.lists.slice().reverse().find(l => l.done > 0); let t = ''; if (ll && !S.nextProject(state)) { ll.done--; t = ll.name; } else { t = state.done.pop(); delete state.sites[t]; } refresh(['Undone', t + ' is back on the path.']); }], ['Simulate a page read: +2 steps', () => { const t = nx ? nx.title : ''; if (!t) return; const st = stepsOf(t); applyProject({ title: t, done: Math.min(st.total, st.done + 2), total: st.total, at: Date.now() }); }]]);
      { const slider = el('input'); slider.type = 'range'; slider.min = '0'; slider.max = '100'; slider.value = String(Math.round(S.power(state, Date.now()) * 100)); slider.setAttribute('aria-label', 'Power override'); slider.addEventListener('input', () => { state.power = +slider.value / 100; save(); paintBuild(); }); const sp = el('input'); sp.type = 'number'; sp.min = '0'; sp.value = String(state.wallet.sparks); sp.setAttribute('aria-label', 'Sparks'); sp.addEventListener('change', () => { state.wallet.sparks = Math.max(0, +sp.value | 0); save(); paintSparks(); paintShop(); }); const cz = el('input'); cz.type = 'number'; cz.min = '1'; cz.value = String(state.life.citizens); cz.setAttribute('aria-label', 'Citizens'); cz.addEventListener('change', () => { state.life.citizens = Math.max(1, +cz.value | 0); state.life.at = Date.now(); save(); paintBuild(); });
        devRow('Power', [slider, ['Auto', () => { delete state.power; }, typeof state.power !== 'number'], ['Built today', () => { delete state.power; state.life.at = Date.now(); state.life.power = 1; }], ['Idle 3 days', () => { delete state.power; state.life.at = Date.now() - 3 * S.REAL_DAY; }], ['Idle a week', () => { delete state.power; state.life.at = Date.now() - 7 * S.REAL_DAY; }], el('span', null, 'Sparks'), sp, el('span', null, 'Citizens'), cz]); }
      devRow('Time', [['Day = 5 s', () => { state.dayMs = 5000; }, state.dayMs === 5000], ['40 s', () => { delete state.dayMs; }, !state.dayMs], ['2 min', () => { state.dayMs = 120000; }, state.dayMs === 120000], ['Skip a month', () => { state.life.founded -= 30 * S.dayMs(state); }], ['Crew: skip a day', () => { state.life.crewAt -= S.REAL_DAY; const b = S.crew(state, Date.now()); if (b.length) btoast('Crew built ' + b.join(', ')); }], el('span', null, 'Clock')].concat([['Live', null], ['Day', 12], ['Dusk', 19], ['Night', 23]].map(([t, h]) => [t, () => { if (h == null) delete state.hour; else state.hour = h; }, (h == null && typeof state.hour !== 'number') || state.hour === h])));
      devRow('Land', Land.TERRAIN_KEYS.map(k => [TERRAIN_ICON[k] + ' ' + Land.TERRAINS[k].name, () => { state.biome = k; S.forget(); }, state.biome === k]).concat([['Quiet (no people, no weather)', () => { state.quiet = !state.quiet; }, !!state.quiet]]));
      { fpsSpan = el('span', 'fps', ''); const ex = el('button', null, 'Export / import state'); ex.type = 'button'; ioBox = el('textarea'); ioBox.hidden = true; ioBox.setAttribute('aria-label', 'State as JSON'); ex.addEventListener('click', () => { ioBox.hidden = !ioBox.hidden; if (!ioBox.hidden) ioBox.value = JSON.stringify(state); }); const imp = el('button', null, 'Load JSON'); imp.type = 'button'; imp.addEventListener('click', () => { try { const o = JSON.parse(ioBox.value); Object.assign(state, S.normalise(o)); save(); S.forget(); lastL = S.layout(state); refresh(['Loaded', 'State replaced.']); paintDev(); paintBuild(); paintBoard(); paintSparks(); } catch (err) { btoast('Not JSON'); } });
        devRow('Tools', [ex, imp, fpsSpan]); devbar.appendChild(ioBox); } }

    /* ---- the loop: draw only what is showing; one frame in flight at a time ---- */
    let running = true, pending = 0, lastCrew = 0, lastPip = 0;
    function frame(now) {
      pending = 0; if (!running) return;
      if (perf.t) perf.ema = perf.ema * 0.95 + (now - perf.t) * 0.05; perf.t = now; if (fpsSpan && Math.floor(now / 500) !== Math.floor((now - perf.ema) / 500)) setText(fpsSpan, Math.round(1000 / perf.ema) + ' fps');
      const night = S.nightOf(S.hourOf(state));
      { const e = E.eraOf(state); if (e.name !== lastEra) { lastEra = e.name; if (E.level(state) > 0) { show('base'); showLevelUp(e); Land.goTo(me, lastL.paths, [S.HOME[0] + 1.5, S.HOME[1] + 2.5]); me.follow = true; } } }
      if (now - lastCrew > 5000) { lastCrew = now; const built = S.crew(state, Date.now()); if (built.length) { save(); lastL = S.layout(state); btoast('The crew built ' + built[0]); paintBuild(); } }
      if (now - lastPip > 90000 && S.nextProject(state) && current === 'base') { lastPip = now; bsay('Still here?', 'Your next step is waiting.', ['Build', () => show('build')]); }
      if (current === 'world') { world.ctx.setTransform(1, 0, 0, 1, 0, 0); Land.sky({ ctx: world.ctx, W: world.PW, H: world.PH }, night); world.reset(); world.night = night; HQ.drawHQ(world, state, now, {}); }
      else if (current === 'avatar') { const ac = camTo(2, 2, avI.H); avI.cam.x = ac.x; avI.cam.y = ac.y + 10; Land.sky(avI, night); avI.night = night; for (let y = 0; y < 5; y++) for (let x = 0; x < 5; x++) avI.tile(x, y, y === 2 ? '#c8a877' : Land.groundColour(x + 30, y + 30), y === 2 ? 'rgba(110,75,30,.35)' : null); B.oak(avI, 4, 0, 0.9); B.hay(avI, 0, 4); avI.lamp(4.5, 2.5); const t = (now / 2600) % 1; B.avatar(avI, 0.5 + t * 4, 2.5, av, now / 1000, true); avI.nightfall(night); }
      else if (current === 'base') { Land.stepMe(me, lastL.paths); if (me.follow) { const c = camTo(me.gx, me.gy, base.H); base.cam.x = lerp(base.cam.x, c.x, reduce ? 1 : 0.08); base.cam.y = lerp(base.cam.y, c.y, reduce ? 1 : 0.08); } Land.sky(base, night); base.night = night; Land.drawLand(base, state, me, now, { anim, fx, placing, land: S.landName(state), quiet: !!state.quiet }); const era = E.eraOf(state), nx = S.nextProject(state); setText(shield, String(E.level(state) + 1)); setText(whoS, era.name + ' · ' + E.score(state) + ' built · ' + S.population(state, Date.now(), lastL.capacity) + ' live here · ' + Math.round(S.power(state, Date.now()) * 100) + '%'); setText(whoN, nx ? 'Next: ' + nx.title + ' →' : 'Everything is built'); if (anim && now - anim.start > 1700) anim = null; while (fx.length && now - fx[0].start > fx[0].life) fx.shift(); if (!reduce && me.moving) { if (!state.me) state.me = { gx: 0, gy: 0 }; state.me.gx = me.gx; state.me.gy = me.gy; } lastL = S.layout(state); }
      else if (current === 'build') { Land.sky(site, night); site.night = night; const st = current_site ? stepsOf(current_site.title) : { done: 0, total: 0 }; const o = { site: current_site, stepsDone: st.done, stepsTotal: st.total, k: reduce ? 1 : clamp((now - bs.lastAt) / 900, 0, 1), anim, quiet: !!state.quiet }; Land.drawLand(site, state, null, now, o); setText(sbadge, o.stage ? o.stage + ' · ' + st.done + ' of ' + st.total : '');
        /* the nail game: while something is going up, nails pop up round the site; tap them */
        if (current_site && st.done > 0 && st.done < st.total && !reduce) { if (now - game.last > 1400 && game.nails.filter(n => !n.done).length < 4) { game.last = now; const slot = [[0.1, 0.1], [0.9, 0.1], [0.1, 0.9], [0.9, 0.9], [0.5, 0.1], [0.5, 0.9]][Math.floor(Math.random() * 6)]; game.nails.push({ gx: current_site.gx + slot[0], gy: current_site.gy + slot[1], z: 36, born: now, done: false }); } game.nails = game.nails.filter(n => n.done ? now - n.at < 500 : now - n.born < 7000); game.nails.forEach(n => { const q = site.p(n.gx, n.gy, n.z); n.sx = q[0]; n.sy = q[1]; }); game.nails.forEach(n => { const ctx = site.ctx; if (n.done) { const t = (now - n.at) / 500; ctx.globalAlpha = 1 - t; ctx.font = '800 12px Baloo 2, system-ui, sans-serif'; ctx.fillStyle = '#ffc531'; ctx.textAlign = 'center'; ctx.fillText('+1', n.sx, n.sy - 10 - t * 16); ctx.textAlign = 'left'; ctx.globalAlpha = 1; return; } const pulse = 1 + Math.sin((now - n.born) / 150) * 0.15; ctx.fillStyle = 'rgba(255,197,49,.35)'; ctx.beginPath(); ctx.arc(n.sx, n.sy, 13 * pulse, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = '#ffc531'; ctx.lineWidth = 1.5; ctx.beginPath(); ctx.arc(n.sx, n.sy, 13 * pulse, 0, Math.PI * 2); ctx.stroke(); ctx.fillStyle = '#9aa3b0'; ctx.fillRect(n.sx - 1.5, n.sy - 9, 3, 11); ctx.fillStyle = '#e6e9ef'; ctx.fillRect(n.sx - 4, n.sy - 11, 8, 3); }); } }
      else if (current === 'global') { if (gview.spin && !reduce) gview.yaw += 0.08; ghits = G.drawGlobe(gctx, g1.cv.width, g1.cv.height, state, now, gview); setText(gsmall, state.mode === 'dev' ? 'sample plots' : 'plots when NextWork publishes a count'); }
      if (!reduce && !pending) pending = requestAnimationFrame(frame);
    }
    paintMode(); paintDev(); paintBuild(); paintBoard(); paintSparks();
    const remembered = host.remember && host.remember('tab'); show(!state.biome ? 'base' : TABS.some(t => t[0] === remembered) ? remembered : 'world');
    pending = requestAnimationFrame(frame); if (reduce) { const keep = current; ['world', 'avatar', 'base', 'build', 'global'].forEach(v => { current = v; frame(0); }); current = keep; }
    return { state, show, finish, theme, repaint() { paintBuild(); paintBoard(); paintDev(); paintSparks(); }, applyProject, applyPortfolio(r) { S.applyPortfolioReading(state, r); save(); lastL = S.layout(state); paintBuild(); }, pause() { running = false; }, resume() { if (!running) { running = true; if (!pending) pending = requestAnimationFrame(frame); } } };
  }
  NW.mount = mount;
})();
