#!/usr/bin/env node
/* Run the independent reviewers against a pull request.
 *
 *     node tools/review-pr.js <pr-number>
 *     node tools/review-pr.js <pr-number> --dry-run   (print, post nothing)
 *
 * Each reviewer reads the diff and posts its findings as a pull request
 * comment. The script prints a verdict and exits non-zero unless every
 * reviewer passed.
 *
 * What this script deliberately does NOT do:
 *
 *   - It never approves. A review comment is not an approval, and the
 *     reviewers have no way to give one.
 *   - It never merges.
 *
 * Approving and merging belong to the maintainer. That is the entire point of
 * the gate: two independent reads happen first, a human decides afterwards.
 *
 * A reviewer that cannot run counts as a BLOCK, never as a pass. A gate that
 * opens when its checker is broken is not a gate.
 */
'use strict';

const { execFileSync, spawnSync } = require('node:child_process');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');

/* The reviewers. Swapping one is a single entry here: a name, the command,
 * and the arguments that put it in non-interactive mode.
 *
 * The prompt goes in on stdin, never as an argument. Windows caps a command
 * line at about 32,000 characters, and a prompt carrying a diff passes that
 * easily - the first run of this script failed with "The command line is too
 * long" on a 15 KB diff. Both of these read stdin: `codex exec -` takes its
 * instructions from it, and `gemini -p` appends its argument to it. */
const REVIEWERS = [
  { name: 'Codex',  cmd: 'codex',  args: ['exec', '-'] },
  { name: 'Gemini', cmd: 'gemini',
    args: ['-p', 'Follow the review instructions given above and end with the VERDICT line.'] }
];

const VERDICT_LINE = /VERDICT:\s*(PASS|BLOCK)/i;
const MAX_DIFF = 120000;        /* characters; beyond this a review is guesswork */

function sh(cmd, args, opts) {
  return execFileSync(cmd, args, Object.assign({
    cwd: ROOT, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024
  }, opts || {}));
}

function prompt(pr, title, body, diff) {
  return [
    'You are one of two independent reviewers on a pull request. Another',
    'reviewer is reading the same diff separately. You are NOT approving it:',
    'a human maintainer decides that afterwards. Your job is to find what is',
    'wrong with it.',
    '',
    'The project is a Manifest V3 browser extension that re-themes a website.',
    'It has no runtime dependencies. House rules, enforced by tools/audit.js:',
    '',
    '  - No network calls of any kind. No fetch, XMLHttpRequest, WebSocket,',
    '    sendBeacon, or remote URLs.',
    '  - No eval, no new Function, no innerHTML.',
    '  - The only browser permission is storage.',
    '  - Body text must clear a 7:1 contrast ratio; secondary text 4.5:1.',
    '  - Plain ES5-style JavaScript. No framework, no bundler.',
    '  - Generated files (assets/, docs/img/themes.svg, src/wallpapers.js,',
    '    icons/) must be regenerated by their tool, never hand-edited.',
    '',
    'Review the diff below for, in order of importance:',
    '',
    '  1. Correctness bugs. Say concretely what input produces what wrong',
    '     result. A vague worry is not a finding.',
    '  2. Security problems, especially anything that could exfiltrate data',
    '     from a page the user is logged in to.',
    '  3. Breaches of the house rules above.',
    '  4. Missing tests for behaviour the diff changes.',
    '',
    'Be specific and brief. Cite file and line. If the diff is fine, say so',
    'rather than inventing work. Do not comment on style preferences that the',
    'surrounding code already settles.',
    '',
    'End your reply with exactly one line, on its own:',
    '',
    '  VERDICT: PASS      (nothing here should block a merge)',
    '  VERDICT: BLOCK     (at least one finding should be fixed first)',
    '',
    '--- PULL REQUEST #' + pr + ': ' + title + ' ---',
    '',
    (body || '(no description)').slice(0, 4000),
    '',
    '--- DIFF ---',
    '',
    diff
  ].join('\n');
}

/* These CLIs install as .cmd shims on Windows, which cannot be executed
 * without a shell - and a shell then re-splits the arguments, so anything
 * containing a space has to be quoted back together. */
function shellArg(a) {
  return /[\s"&|<>^()]/.test(a) ? '"' + a.replace(/"/g, '\\"') + '"' : a;
}

function runReviewer(reviewer, text) {
  const useShell = process.platform === 'win32';
  const args = useShell ? reviewer.args.map(shellArg) : reviewer.args;
  const r = spawnSync(reviewer.cmd, args, {
    cwd: ROOT, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024,
    shell: useShell,
    input: text                     /* the prompt, never on the command line */
  });

  if (r.error) {
    return { ok: false, verdict: 'BLOCK', output:
      'This reviewer could not be run: ' + r.error.message +
      '\n\nA reviewer that cannot run is treated as a block, not as a pass.' };
  }
  const output = ((r.stdout || '') + (r.stderr || '')).trim();
  if (r.status !== 0 && !output) {
    return { ok: false, verdict: 'BLOCK', output:
      'This reviewer exited with code ' + r.status + ' and said nothing.' };
  }
  const m = VERDICT_LINE.exec(output);
  if (!m) {
    return { ok: false, verdict: 'BLOCK', output: output +
      '\n\n---\n\nNo VERDICT line was found in this reply, so it is counted as a block.' };
  }
  return { ok: m[1].toUpperCase() === 'PASS', verdict: m[1].toUpperCase(), output: output };
}

function comment(pr, reviewer, result, dryRun) {
  const mark = result.verdict === 'PASS' ? '✅' : '⛔';
  const body = [
    '## ' + mark + ' ' + reviewer.name + ' review — ' + result.verdict,
    '',
    '_Automated review from `' + reviewer.cmd + '` via `tools/review-pr.js`.',
    'This is a review, not an approval. Approving and merging are the',
    "maintainer's, and only the maintainer's._",
    '',
    '---',
    '',
    result.output
  ].join('\n');

  if (dryRun) {
    console.log('\n----- would post to PR #' + pr + ' -----\n' + body + '\n');
    return;
  }
  sh('gh', ['pr', 'comment', String(pr), '--body', body]);
  console.log('  posted ' + reviewer.name + ' review to PR #' + pr);
}

function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const pr = args.find(a => /^\d+$/.test(a));
  if (!pr) {
    console.error('usage: node tools/review-pr.js <pr-number> [--dry-run]');
    process.exit(2);
  }

  let meta;
  try {
    meta = JSON.parse(sh('gh', ['pr', 'view', pr, '--json', 'title,body,state']));
  } catch (e) {
    console.error('Could not read PR #' + pr + '. Is `gh` signed in?');
    process.exit(2);
  }
  if (meta.state !== 'OPEN') {
    console.error('PR #' + pr + ' is ' + meta.state + '. Nothing to review.');
    process.exit(2);
  }

  let diff = sh('gh', ['pr', 'diff', pr]);
  if (diff.length > MAX_DIFF) {
    /* Truncating is honest; silently reviewing a fraction of a change is not. */
    diff = diff.slice(0, MAX_DIFF) +
      '\n\n[diff truncated at ' + MAX_DIFF + ' characters. Split this pull ' +
      'request: a review of part of a change is not a review of the change.]';
  }

  const text = prompt(pr, meta.title, meta.body, diff);
  console.log('Reviewing PR #' + pr + ': ' + meta.title);
  console.log(diff.length + ' characters of diff, ' + REVIEWERS.length + ' reviewers\n');

  const results = [];
  REVIEWERS.forEach(function (reviewer) {
    console.log('  running ' + reviewer.name + ' (' + reviewer.cmd + ')...');
    const result = runReviewer(reviewer, text);
    console.log('  ' + reviewer.name + ': ' + result.verdict);
    comment(pr, reviewer, result, dryRun);
    results.push({ reviewer: reviewer, result: result });
  });

  console.log('\n--- verdicts ---');
  results.forEach(function (r) {
    console.log('  ' + r.reviewer.name.padEnd(8) + r.result.verdict);
  });

  const blocked = results.filter(r => !r.result.ok);
  if (blocked.length) {
    console.log('\n' + blocked.length + ' of ' + results.length +
                ' reviewers blocked. Fix the findings and run this again.');
    process.exit(1);
  }
  console.log('\nBoth reviewers passed.');
  console.log('This does NOT merge the pull request. Hand it to the maintainer,');
  console.log('who reviews the findings and merges if satisfied.');
}

main();
